/// Renders the `JNI_OnLoad` function that calls `RegisterNatives` for every
/// `@WireletObservable` class configured via the JNI registration sidecar.
///
/// Only ONE `JNI_OnLoad` is emitted per `.so`. When multiple view-models are
/// present, all `FindClass` + `RegisterNatives` calls are consolidated into a
/// single function body. The output is wrapped in `#if os(Android) … #endif`
/// so it compiles to nothing on Apple platforms.
public enum JNIOnLoadEmitter {
    /// Renders the full `__WireletObservableJNI_OnLoad.swift` file content
    /// given the list of view-model registrations from the sidecar config.
    ///
    /// - Parameter viewModels: One entry per `@WireletObservable` class.
    ///   Must be non-empty; the caller is responsible for guarding.
    /// - Returns: Complete Swift source text for the JNI_OnLoad file.
    public static func renderFile(viewModels: [ViewModelRegistration]) -> String {
        let body = renderFunction(viewModels: viewModels)
        return """
        // Generated by emit-wirelet-observable-swift-bridges.
        // Do not edit by hand.
        #if os(Android)
        import Android
        import SwiftJavaJNICore

        \(body)
        #endif
        """
    }

    // MARK: - Function body

    private static func renderFunction(viewModels: [ViewModelRegistration]) -> String {
        let registrationBlocks = viewModels.map { vm in
            renderRegistrationBlock(for: vm)
        }.joined(separator: "\n\n")

        return """
        private let JNI_VERSION_1_6: jint = 0x0001_0006

        @_cdecl("JNI_OnLoad")
        public func JNI_OnLoad(
            _ vm: UnsafeMutablePointer<JavaVM?>?,
            _ reserved: UnsafeMutableRawPointer?
        ) -> jint {
            guard let vm, let vmFns = vm.pointee?.pointee else {
                return JNI_ERR
            }

            // Register the adopted JVM as the shared instance so that
            // JObject's `JavaVirtualMachine.shared()` returns it directly
            // instead of falling back to dlopen + JNI_GetCreatedJavaVMs on
            // first use.
            JavaVirtualMachine.setShared(JavaVirtualMachine(adoptingJVM: vm))

            var envRaw: UnsafeMutableRawPointer?
            let getEnvResult = vmFns.GetEnv(vm, &envRaw, JNI_VERSION_1_6)
            guard getEnvResult == JNI_OK, let envRaw else { return JNI_ERR }
            let env = envRaw.assumingMemoryBound(to: JNIEnv?.self)
            guard let envFns = env.pointee?.pointee else { return JNI_ERR }

        \(registrationBlocks.indented(by: 4))

            return JNI_VERSION_1_6
        }
        """
    }

    private static func renderRegistrationBlock(for vm: ViewModelRegistration) -> String {
        let cls = vm.swiftClass
        let methodTableVar = "__methods_\(cls)"
        let methodRows = vm.nativeMethods.map { m in
            renderMethodRow(m, className: cls)
        }.joined(separator: "\n")

        return """
        // \(cls) → \(vm.kotlinClassFQN)
        guard let __cls_\(cls) = "\(vm.kotlinClassFQN)".withCString({ envFns.FindClass(env, $0) }) else {
            return JNI_ERR
        }
        do {
            var nameStorage_\(cls): [UnsafeMutablePointer<CChar>] = []
            var sigStorage_\(cls): [UnsafeMutablePointer<CChar>] = []
            nameStorage_\(cls).reserveCapacity(\(vm.nativeMethods.count))
            sigStorage_\(cls).reserveCapacity(\(vm.nativeMethods.count))
            defer {
                nameStorage_\(cls).forEach { free($0) }
                sigStorage_\(cls).forEach { free($0) }
            }
            var \(methodTableVar): [JNINativeMethod] = []
            \(methodTableVar).reserveCapacity(\(vm.nativeMethods.count))
        \(methodRows.indented(by: 8))
            let regResult_\(cls) = \(methodTableVar).withUnsafeMutableBufferPointer { buf -> jint in
                envFns.RegisterNatives(env, __cls_\(cls), buf.baseAddress, jint(buf.count))
            }
            guard regResult_\(cls) == JNI_OK else { return JNI_ERR }
        }
        """
    }

    private static func renderMethodRow(_ m: NativeMethod, className: String) -> String {
        let methodEntry = "JNINativeMethod(name: cName_\(m.name), "
            + "signature: cSig_\(m.name), fnPtr: fn_\(m.name))"
        return """
        do {
            guard let fn_\(m.name) = "\(m.cdeclSymbol)".withCString({ dlsym(nil, $0) }) else { return JNI_ERR }
            guard let cName_\(m.name) = strdup("\(m.name)"),
                  let cSig_\(m.name) = strdup("\(m.signature)") else { return JNI_ERR }
            nameStorage_\(className).append(cName_\(m.name))
            sigStorage_\(className).append(cSig_\(m.name))
            __methods_\(className).append(\(methodEntry))
        }
        """
    }
}

// MARK: - String indentation helper

extension String {
    /// Prepends `count` spaces to every non-empty line.
    fileprivate func indented(by count: Int) -> String {
        let prefix = String(repeating: " ", count: count)
        return split(separator: "\n", omittingEmptySubsequences: false)
            .map { line -> String in line.isEmpty ? "" : prefix + line }
            .joined(separator: "\n")
    }
}
