// JNI_OnLoad: wire generated Kotlin `external fun nativeXxx(...)` declarations
// to the Swift `@_cdecl("WireletObservable_TodoListVM_*")` symbols emitted by
// the WireletObservableBridges build tool plugin.
//
// Why this is hand-written (and not generated by the plugin):
// JNI's auto-resolution maps `external fun nativeFoo()` to a C symbol named
// `Java_<kotlin_package_with_slashes>_<class>_nativeFoo`. Our `@_cdecl`
// symbols use a flat `WireletObservable_<Class>_<member>` convention that
// the Swift bridge plugin doesn't know how to align with the Kotlin
// emitter's package — there's no config flow from the Wirelet Gradle
// plugin to the SwiftPM build tool plugin yet.
//
// Phase 4b follow-up: have the plugin emit a JNI_OnLoad like this one
// automatically, parameterised by a per-class Kotlin FQN config.
#if os(Android)
import Android
import CWireletJNI

// Each row: (Kotlin method name, JNI signature, Swift @_cdecl symbol name).
// Order and signatures MUST match the generated TodoListVMViewModel.kt —
// see the `external fun nativeXxx(...)` declarations there.
private let nativeMethodSpecs: [(name: String, signature: String, symbol: String)] = [
    ("nativeNew", "()J", "WireletObservable_TodoListVM_new"),
    ("nativeRelease", "(J)V", "WireletObservable_TodoListVM_release"),
    ("nativeItemsTrack", "(JLjava/lang/Runnable;)[B", "WireletObservable_TodoListVM_items_track"),
    ("nativeFilterTrack", "(JLjava/lang/Runnable;)Ljava/lang/String;", "WireletObservable_TodoListVM_filter_track"),
    ("nativeTotalCountTrack", "(JLjava/lang/Runnable;)I", "WireletObservable_TodoListVM_totalCount_track"),
    ("nativeItemsSet", "(J[B)V", "WireletObservable_TodoListVM_items_set"),
    ("nativeFilterSet", "(JLjava/lang/String;)V", "WireletObservable_TodoListVM_filter_set"),
    ("nativeTotalCountSet", "(JI)V", "WireletObservable_TodoListVM_totalCount_set"),
    ("nativeAdd", "(J[B)V", "WireletObservable_TodoListVM_add_invoke"),
    ("nativeClear", "(J)V", "WireletObservable_TodoListVM_clear_invoke"),
]

// JNI's internal class name (slashes, not dots).
private let kotlinViewModelInternalName =
    "io/github/jiyimeta/observablecounter/generated/TodoListVMViewModel"

private let JNI_VERSION_1_6: jint = 0x0001_0006

@_cdecl("JNI_OnLoad")
public func JNI_OnLoad(
    _ vm: UnsafeMutablePointer<JavaVM?>?,
    _ reserved: UnsafeMutableRawPointer?
) -> jint {
    guard let vm, let vmFns = vm.pointee?.pointee else {
        return JNI_ERR
    }

    // GetEnv(JavaVM*, void**, jint) → writes JNIEnv* into the void* slot.
    var envRaw: UnsafeMutableRawPointer?
    let getEnvResult = vmFns.GetEnv(vm, &envRaw, JNI_VERSION_1_6)
    guard getEnvResult == JNI_OK, let envRaw else { return JNI_ERR }
    let env = envRaw.assumingMemoryBound(to: JNIEnv?.self)
    guard let envFns = env.pointee?.pointee else { return JNI_ERR }

    guard let cls = kotlinViewModelInternalName.withCString({ name in
        envFns.FindClass(env, name)
    }) else {
        // Defensive: if the consumer triggers System.loadLibrary BEFORE the
        // ViewModel class is loaded, FindClass returns null. The plan
        // assumes Compose's eager VM init covers this; if not, we'd need
        // to defer registration to first invocation.
        return JNI_ERR
    }

    // Build JNINativeMethod[]; each entry holds (name, sig, fnPtr).
    // dlsym with RTLD_DEFAULT (NULL on bionic) finds @_cdecl symbols by name
    // without spelling their Swift identifiers.
    var nameStorage: [UnsafeMutablePointer<CChar>] = []
    var sigStorage: [UnsafeMutablePointer<CChar>] = []
    nameStorage.reserveCapacity(nativeMethodSpecs.count)
    sigStorage.reserveCapacity(nativeMethodSpecs.count)
    defer {
        nameStorage.forEach { free($0) }
        sigStorage.forEach { free($0) }
    }

    var methods: [JNINativeMethod] = []
    methods.reserveCapacity(nativeMethodSpecs.count)
    for spec in nativeMethodSpecs {
        let fnPtr: UnsafeMutableRawPointer? = spec.symbol.withCString { symbolC in
            // RTLD_DEFAULT on bionic is NULL.
            dlsym(nil, symbolC)
        }
        guard let fnPtr else {
            // A bridge symbol is missing — the plugin emitted it wrong.
            return JNI_ERR
        }
        guard let cName = strdup(spec.name), let cSig = strdup(spec.signature) else {
            return JNI_ERR
        }
        nameStorage.append(cName)
        sigStorage.append(cSig)
        methods.append(JNINativeMethod(name: cName, signature: cSig, fnPtr: fnPtr))
    }

    let registerResult = methods.withUnsafeMutableBufferPointer { buf -> jint in
        envFns.RegisterNatives(env, cls, buf.baseAddress, jint(buf.count))
    }
    guard registerResult == JNI_OK else { return JNI_ERR }

    return JNI_VERSION_1_6
}
#endif
