import Foundation
import Testing
import WireletProvidedSwiftBridgesEmitter

@Suite("ProvidedSwiftBridgesEmitterTests")
struct ProvidedSwiftBridgesEmitterTests {

    private func writeTmp(name: String, content: String) throws -> URL {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("provided-emitter-tests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appendingPathComponent(name)
        try content.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    // MARK: - The golden TodoStore (matches the Phase 0 hand-written proxy)

    @Test func todoStoreGolden() throws {
        let source = """
        import Wirelet
        import WireletProvided

        @WireletProvided
        protocol TodoStore {
            func loadAll() -> [TodoItem]
            func add(_ item: TodoItem)
            func remove(_ id: Int32)
        }
        """
        let url = try writeTmp(name: "TodoStore.swift", content: source)
        let results = try ProvidedSwiftBridgesEmitter().emit(sources: [url])
        #expect(results.count == 1)
        let (name, content) = results[0]
        #expect(name == "TodoStore+WireletProxy.swift")

        // Header + Android guard + imports
        #expect(content.contains("// Generated by emit-wirelet-provided-swift-bridges."))
        #expect(content.contains("#if os(Android)"))
        #expect(content.contains("import Wirelet"))
        #expect(content.contains("import WireletObservable"))
        #expect(content.contains("#endif"))

        // Class shape
        #expect(content.contains("final class TodoStoreWireletProxy: TodoStore {"))
        #expect(content.contains("let adapter: JObject"))
        #expect(content.contains("init(adapter: JObject) {"))

        // loadAll() -> [TodoItem] : callBytes + list decode
        #expect(content.contains("func loadAll() -> [TodoItem] {"))
        #expect(content.contains(#"adapter.callBytes(method: "loadAllWire", signature: "()[B")"#))
        #expect(content.contains("var reader = WireFormatReader(data: Data(bytes))"))
        #expect(content.contains("try? TodoItem(from: &reader)"))

        // add(_ item: TodoItem) : encode single value, void call
        #expect(content.contains("func add(_ item: TodoItem) {"))
        #expect(content.contains("let arg0Bytes = [UInt8](item.encodeToData())"))
        #expect(content.contains(#"adapter.callVoid(method: "addWire", signature: "([B)V", [.bytes(arg0Bytes)])"#))

        // remove(_ id: Int32) : primitive int arg, void call
        #expect(content.contains("func remove(_ id: Int32) {"))
        #expect(content.contains(#"adapter.callVoid(method: "removeWire", signature: "(I)V", [.int(Int32(id))])"#))
    }

    // MARK: - Primitive / bool / string / float / double returns and args

    @Test func scalarReturnsAndArgs() throws {
        let source = """
        import WireletProvided
        @WireletProvided
        protocol Calc {
            func ping()
            func count() -> Int32
            func total() -> Int64
            func ratio() -> Double
            func magnitude() -> Float
            func enabled() -> Bool
            func name() -> String
            func configure(_ scale: Double, _ label: String, _ flag: Bool, _ big: Int64)
        }
        """
        let url = try writeTmp(name: "Calc.swift", content: source)
        let results = try ProvidedSwiftBridgesEmitter().emit(sources: [url])
        #expect(results.count == 1)
        let content = results[0].content

        #expect(content.contains(#"adapter.callVoid(method: "pingWire", signature: "()V")"#))
        #expect(content.contains(#"return Int32(adapter.callInt(method: "countWire", signature: "()I") ?? 0)"#))
        #expect(content.contains(#"return Int64(adapter.callLong(method: "totalWire", signature: "()J") ?? 0)"#))
        #expect(content.contains(#"return adapter.callDouble(method: "ratioWire", signature: "()D") ?? 0"#))
        #expect(content.contains(#"return adapter.callFloat(method: "magnitudeWire", signature: "()F") ?? 0"#))
        #expect(content.contains(#"return adapter.callBool(method: "enabledWire", signature: "()Z") ?? false"#))
        #expect(content.contains(#"return adapter.callString(method: "nameWire", signature: "()Ljava/lang/String;") ?? """#))

        // Mixed args build the right descriptor + Arg list.
        #expect(content.contains("func configure(_ scale: Double, _ label: String, _ flag: Bool, _ big: Int64) {"))
        #expect(content.contains(#"signature: "(DLjava/lang/String;ZJ)V""#))
        #expect(content.contains("[.double(scale), .string(label), .bool(flag), .long(Int64(big))]"))
    }

    // MARK: - Array argument (encode count + payloads)

    @Test func arrayArgument() throws {
        let source = """
        import WireletProvided
        @WireletProvided
        protocol Bulk {
            func addAll(_ items: [TodoItem])
        }
        """
        let url = try writeTmp(name: "Bulk.swift", content: source)
        let content = try ProvidedSwiftBridgesEmitter().emit(sources: [url])[0].content
        #expect(content.contains("var writer0 = WireFormatWriter()"))
        #expect(content.contains("writer0.writeVarint(UInt64(items.count))"))
        #expect(content.contains("for element in items { element.encode(into: &writer0) }"))
        #expect(content.contains("let arg0Bytes = [UInt8](writer0.data)"))
        #expect(content.contains(#"adapter.callVoid(method: "addAllWire", signature: "([B)V", [.bytes(arg0Bytes)])"#))
    }

    // MARK: - Single @WireFormat return traps on missing/invalid bytes

    @Test func wireFormatReturn() throws {
        let source = """
        import WireletProvided
        @WireletProvided
        protocol Single {
            func current() -> TodoItem
        }
        """
        let url = try writeTmp(name: "Single.swift", content: source)
        let content = try ProvidedSwiftBridgesEmitter().emit(sources: [url])[0].content
        #expect(content.contains(#"adapter.callBytes(method: "currentWire", signature: "()[B")"#))
        #expect(content.contains("let value = try? TodoItem(decoding: Data(bytes))"))
        #expect(content.contains(#"fatalError("SingleWireletProxy.current: missing or invalid TodoItem from Kotlin")"#))
        #expect(content.contains("return value"))
    }

    // MARK: - Optionals are deferred — emitter throws

    @Test func optionalReturnThrows() throws {
        let source = """
        import WireletProvided
        @WireletProvided
        protocol Finder {
            func find(_ id: Int32) -> TodoItem?
        }
        """
        let url = try writeTmp(name: "Finder.swift", content: source)
        #expect(throws: ProvidedSwiftBridgesEmitterError.self) {
            _ = try ProvidedSwiftBridgesEmitter().emit(sources: [url])
        }
    }

    @Test func optionalParameterThrows() throws {
        let source = """
        import WireletProvided
        @WireletProvided
        protocol Setter {
            func setLabel(_ label: String?)
        }
        """
        let url = try writeTmp(name: "Setter.swift", content: source)
        #expect(throws: ProvidedSwiftBridgesEmitterError.self) {
            _ = try ProvidedSwiftBridgesEmitter().emit(sources: [url])
        }
    }

    // MARK: - Non-provided / non-swift inputs produce nothing

    @Test func plainProtocolProducesNoResults() throws {
        let source = """
        protocol Plain {
            func foo()
        }
        """
        let url = try writeTmp(name: "Plain.swift", content: source)
        let results = try ProvidedSwiftBridgesEmitter().emit(sources: [url])
        #expect(results.isEmpty)
    }

    @Test func nonSwiftFileIgnored() throws {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("ignore-\(UUID().uuidString).txt")
        try "hello".write(to: url, atomically: true, encoding: .utf8)
        let results = try ProvidedSwiftBridgesEmitter().emit(sources: [url])
        #expect(results.isEmpty)
    }

    // MARK: - Multiple services in one file -> multiple files

    @Test func multipleServicesProduceMultipleFiles() throws {
        let source = """
        import WireletProvided
        @WireletProvided
        protocol A { func a() }
        @WireletProvided
        protocol B { func b() }
        """
        let url = try writeTmp(name: "Two.swift", content: source)
        let results = try ProvidedSwiftBridgesEmitter().emit(sources: [url])
        #expect(results.count == 2)
        let names = Set(results.map(\.name))
        #expect(names == ["A+WireletProxy.swift", "B+WireletProxy.swift"])
    }
}
