import SwiftSyntaxMacros
import SwiftSyntaxMacrosTestSupport
@testable import WireletObservableMacros
import XCTest

private let macroSpecs: [String: any Macro.Type] = [
    "WireletObservable": WireletObservableMacro.self,
    "WireletExpose": WireletExposeMacro.self,
]

// MARK: - Diagnostics (macro is now diagnostic-only; bridges generated by plugin)

final class WireletObservableMacroDiagnosticsTests: XCTestCase {
    func testNonFinalClassEmitsDiagnostic() {
        assertMacroExpansion(
            """
            @WireletObservable
            @Observable
            class Foo {
                var x: Int32 = 0
            }
            """,
            expandedSource: """
            @Observable
            class Foo {
                var x: Int32 = 0
            }
            """,
            diagnostics: [
                .init(message: "@WireletObservable requires a final class.", line: 3, column: 7),
            ],
            macros: macroSpecs,
        )
    }

    func testMissingObservableEmitsDiagnostic() {
        assertMacroExpansion(
            """
            @WireletObservable
            final class Foo {
                var x: Int32 = 0
            }
            """,
            expandedSource: """
            final class Foo {
                var x: Int32 = 0
            }
            """,
            diagnostics: [
                .init(message: "@WireletObservable must be paired with @Observable.", line: 2, column: 13),
            ],
            macros: macroSpecs,
        )
    }

    func multiArgExposedMethodIsAccepted() {
        // Multi-arg @WireletExpose methods are now accepted. The macro is
        // marker-only and emits no code; bridges come from the build tool plugin.
        assertMacroExpansion(
            """
            @WireletObservable
            @Observable
            final class Multi {
                @WireletExpose
                public func twoArgs(_ a: Int32, _ b: Int32) {}
            }
            """,
            expandedSource: """
            @Observable
            final class Multi {
                public func twoArgs(_ a: Int32, _ b: Int32) {}
            }
            """,
            diagnostics: [],
            macros: macroSpecs,
        )
    }

    func primitiveArgExposedMethodIsAccepted() {
        // Single-primitive-arg @WireletExpose methods are now accepted.
        assertMacroExpansion(
            """
            @WireletObservable
            @Observable
            final class Primitive {
                @WireletExpose
                public func setValue(_ value: Int32) {}
            }
            """,
            expandedSource: """
            @Observable
            final class Primitive {
                public func setValue(_ value: Int32) {}
            }
            """,
            diagnostics: [],
            macros: macroSpecs,
        )
    }

    func testValidClassEmitsNoPeers() {
        // A valid @WireletObservable class should expand with no added peers
        // (bridges are now generated by the build tool plugin, not the macro).
        assertMacroExpansion(
            """
            @WireletObservable
            @Observable
            final class CounterVM {
                var count: Int32 = 0
            }
            """,
            expandedSource: """
            @Observable
            final class CounterVM {
                var count: Int32 = 0
            }
            """,
            macros: macroSpecs,
        )
    }
}
