// Auto-generated by emit-wirelet-observable. DO NOT EDIT.
package com.example.app.viewmodels

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

class CounterViewModel internal constructor(
    private val nativePtr: Long
) : ViewModel() {

    private val _count = MutableStateFlow(readCountWithTracking())
    val count: StateFlow<Int> = _count.asStateFlow()

    private fun readCountWithTracking(): Int =
        nativeCountTrack(nativePtr, Runnable {
            viewModelScope.launch(Dispatchers.Main) {
                _count.value = readCountWithTracking()
            }
        })

    fun updateCount(value: Int) {
        nativeCountSet(nativePtr, value)
    }

    override fun onCleared() {
        nativeRelease(nativePtr)
        super.onCleared()
    }

    private external fun nativeCountTrack(self: Long, onChange: Runnable): Int
    private external fun nativeCountSet(self: Long, value: Int)
    private external fun nativeRelease(self: Long)

    companion object {
        init { System.loadLibrary("CounterJNI") }

        fun create(): CounterViewModel =
            CounterViewModel(nativeNew())

        @JvmStatic
        private external fun nativeNew(): Long
    }
}
