// Auto-generated by emit-wirelet-observable. DO NOT EDIT.
package io.github.jiyimeta.observablecounter.generated

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import io.github.jiyimeta.observablecounter.TodoItem
import io.github.jiyimeta.observablecounter.codecs.TodoItemCodec
import io.github.jiyimeta.wirelet.observable.WireletList
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

class TodoListViewModel internal constructor(
    private val nativePtr: Long
) : ViewModel() {

    private val _items = MutableStateFlow(readItemsWithTracking())
    val items: StateFlow<List<TodoItem>> = _items.asStateFlow()

    private val _filter = MutableStateFlow(readFilterWithTracking())
    val filter: StateFlow<String> = _filter.asStateFlow()

    private val _totalCount = MutableStateFlow(readTotalCountWithTracking())
    val totalCount: StateFlow<Int> = _totalCount.asStateFlow()

    private val _pinned = MutableStateFlow(readPinnedWithTracking())
    val pinned: StateFlow<TodoItem?> = _pinned.asStateFlow()

    private fun readItemsWithTracking(): List<TodoItem> =
        WireletList.decode(nativeItemsTrack(nativePtr, Runnable {
            viewModelScope.launch(Dispatchers.Main) {
                _items.value = readItemsWithTracking()
            }
        }), TodoItemCodec::decodePayload)

    private fun readFilterWithTracking(): String =
        nativeFilterTrack(nativePtr, Runnable {
            viewModelScope.launch(Dispatchers.Main) {
                _filter.value = readFilterWithTracking()
            }
        })

    private fun readTotalCountWithTracking(): Int =
        nativeTotalCountTrack(nativePtr, Runnable {
            viewModelScope.launch(Dispatchers.Main) {
                _totalCount.value = readTotalCountWithTracking()
            }
        })

    private fun readPinnedWithTracking(): TodoItem? =
        nativePinnedTrack(nativePtr, Runnable {
            viewModelScope.launch(Dispatchers.Main) {
                _pinned.value = readPinnedWithTracking()
            }
        })?.let { TodoItemCodec.decode(it) }

    fun updateItems(value: List<TodoItem>) {
        nativeItemsSet(nativePtr, WireletList.encode(value, TodoItemCodec::encodePayload))
    }

    fun updateFilter(value: String) {
        nativeFilterSet(nativePtr, value)
    }

    fun updateTotalCount(value: Int) {
        nativeTotalCountSet(nativePtr, value)
    }

    fun updatePinned(value: TodoItem?) {
        nativePinnedSet(nativePtr, value?.let { TodoItemCodec.encode(it) })
    }

    fun add(item: TodoItem) =
        nativeAdd(nativePtr, TodoItemCodec.encode(item))

    fun clear() = nativeClear(nativePtr)

    override fun onCleared() {
        nativeRelease(nativePtr)
        super.onCleared()
    }

    private external fun nativeItemsTrack(self: Long, onChange: Runnable): ByteArray
    private external fun nativeFilterTrack(self: Long, onChange: Runnable): String
    private external fun nativeTotalCountTrack(self: Long, onChange: Runnable): Int
    private external fun nativePinnedTrack(self: Long, onChange: Runnable): ByteArray?
    private external fun nativeItemsSet(self: Long, value: ByteArray)
    private external fun nativeFilterSet(self: Long, value: String)
    private external fun nativeTotalCountSet(self: Long, value: Int)
    private external fun nativePinnedSet(self: Long, value: ByteArray?)
    private external fun nativeAdd(self: Long, arg0: ByteArray)
    private external fun nativeClear(self: Long)
    private external fun nativeRelease(self: Long)

    companion object {
        init { System.loadLibrary("ObservableCounterJNI") }

        fun create(): TodoListViewModel =
            TodoListViewModel(nativeNew())

        @JvmStatic
        private external fun nativeNew(): Long
    }
}
