import WireletSchema

enum ChoiceEmitter {
    /// Emits a Kotlin codec for a `@WireFormatChoice` sum-type enum using
    /// the TLV format (matches the Swift `@WireFormatChoice` macro).
    ///
    /// Wire layout (mirroring the macro):
    /// * Outer encode wraps in `writeLengthPrefixed`.
    /// * Payload writes a varint discriminator (declaration-order index).
    /// * Each associated value of the selected case is emitted as a TLV
    ///   record tagged 1..N in declaration order.
    /// * Cases without associated values encode as just the discriminator.
    static func emit(
        _ choice: WireChoice,
        kotlinName: String,
        modelPackage: String,
        codecPackage: String,
        serializationPackage: String,
        nameTransform: NameTransform,
    ) -> KotlinFile {
        let codecName = "\(kotlinName)Codec"
        let path = codecPackage.replacingOccurrences(of: ".", with: "/") + "/\(codecName).kt"

        // Imports.
        var referenced = Set<String>()
        for c in choice.cases {
            for field in c.payload {
                collectReferenced(typeText: field.typeText, into: &referenced, transform: nameTransform)
            }
        }
        var importLines = ["import \(modelPackage).\(kotlinName)"]
        importLines += referenced.sorted().map { "import \(modelPackage).\($0)" }
        if serializationPackage != codecPackage {
            importLines.append("import \(serializationPackage).BinaryReader")
            importLines.append("import \(serializationPackage).BinaryWriter")
            importLines.append("import \(serializationPackage).WireFormatException")
            importLines.append("import \(serializationPackage).WireType")
        }
        let allImports = importLines.joined(separator: "\n")

        let encodeBranches = choice.cases.enumerated().map { idx, c in
            emitEncodeBranch(c: c, index: idx, kotlinName: kotlinName, transform: nameTransform)
        }.joined(separator: "\n")

        let decodeBranches = choice.cases.enumerated().map { idx, c in
            emitDecodeBranch(c: c, index: idx, kotlinName: kotlinName, transform: nameTransform)
        }.joined(separator: "\n")

        let content = """
        // Auto-generated by emit-wirelet-kotlin. DO NOT EDIT.
        package \(codecPackage)

        \(allImports)

        public object \(codecName) {
            val WIRE_TYPE: WireType = WireType.LENGTH_DELIMITED

            fun encode(value: \(kotlinName)): ByteArray {
                val w = BinaryWriter()
                w.writeLengthPrefixed { encodePayload(value, this) }
                return w.toByteArray()
            }

            fun encodePayload(value: \(kotlinName), w: BinaryWriter) {
                when (value) {
        \(encodeBranches)
                }
            }

            fun decode(data: ByteArray): \(kotlinName) {
                val r = BinaryReader(data)
                return r.readLengthPrefixed { decodePayload(it) }
            }

            fun decodePayload(r: BinaryReader): \(kotlinName) {
                val disc = r.readVarint()
                return when (disc) {
        \(decodeBranches)
                    else -> throw WireFormatException.UnknownChoiceDiscriminator(disc.toInt())
                }
            }
        }

        """

        return KotlinFile(relativePath: path, content: content)
    }

    private static func emitEncodeBranch(
        c: WireChoiceCase,
        index: Int,
        kotlinName: String,
        transform: NameTransform,
    ) -> String {
        let subtype = "\(kotlinName).\(c.name.capitalizedFirst)"
        var lines: [String] = []
        if c.payload.isEmpty {
            lines.append("            is \(subtype) -> {")
            lines.append("                w.writeVarint(\(index)L)")
            lines.append("            }")
            return lines.joined(separator: "\n")
        }
        lines.append("            is \(subtype) -> {")
        lines.append("                w.writeVarint(\(index)L)")
        for (i, field) in c.payload.enumerated() {
            let tag = i + 1
            let prop = field.label ?? "arg\(i)"
            let wt = StructEmitter.wireTypeRef(for: field.typeText, transform: transform)
            lines.append("                w.writeTag(\(tag), \(wt))")
            let writeLines = StructEmitter.payloadWrite(
                typeText: field.typeText,
                valueExpr: "value.\(prop)",
                writerName: "w",
                transform: transform,
            )
            for ln in writeLines {
                lines.append("                \(ln)")
            }
        }
        lines.append("            }")
        return lines.joined(separator: "\n")
    }

    /// Decode branches sit inside `when (disc) { ... }` at 12-space
    /// indent. Each branch body lines up at 16-space indent.
    private static func emitDecodeBranch(
        c: WireChoiceCase,
        index: Int,
        kotlinName: String,
        transform: NameTransform,
    ) -> String {
        let subtype = "\(kotlinName).\(c.name.capitalizedFirst)"
        if c.payload.isEmpty {
            return "            \(index)L -> \(subtype)"
        }
        var lines: [String] = []
        lines.append("            \(index)L -> {")
        for (i, field) in c.payload.enumerated() {
            let kt = KotlinTypeMap.kotlinType(of: field.typeText, nameTransform: transform)
            lines.append("                var _arg\(i): \(kt)? = null")
        }
        lines.append("                while (r.remaining > 0) {")
        lines.append("                    val (tag, wt) = r.readTag()")
        lines.append("                    when (tag) {")
        for (i, field) in c.payload.enumerated() {
            let tag = i + 1
            let readExpr = StructEmitter.decodeExpr(typeText: field.typeText, readerName: "r", transform: transform)
            lines.append("                        \(tag) -> _arg\(i) = \(readExpr)")
        }
        lines.append("                        else -> r.skipUnknownField(wt)")
        lines.append("                    }")
        lines.append("                }")
        for (i, field) in c.payload.enumerated() {
            let tag = i + 1
            let wt = StructEmitter.wireTypeRef(for: field.typeText, transform: transform)
            lines.append("                val arg\(i) = _arg\(i) ?: throw WireFormatException.UnknownTag(\(tag), \(wt))")
        }
        let constructorArgs = c.payload.enumerated().map { i, field -> String in
            let prop = field.label ?? "arg\(i)"
            return "\(prop) = arg\(i)"
        }.joined(separator: ", ")
        lines.append("                \(subtype)(\(constructorArgs))")
        lines.append("            }")
        return lines.joined(separator: "\n")
    }

    private static func collectReferenced(
        typeText: String,
        into out: inout Set<String>,
        transform: NameTransform,
    ) {
        if KotlinTypeMap.primitive(typeText) != nil { return }
        if let elem = KotlinTypeMap.arrayElementType(typeText) {
            collectReferenced(typeText: elem, into: &out, transform: transform)
            return
        }
        if let (k, v) = KotlinTypeMap.dictionaryTypes(of: typeText) {
            collectReferenced(typeText: k, into: &out, transform: transform)
            collectReferenced(typeText: v, into: &out, transform: transform)
            return
        }
        out.insert(transform.apply(to: KotlinTypeMap.simpleName(of: typeText)))
    }
}

extension String {
    fileprivate var capitalizedFirst: String {
        guard let first else { return self }
        return first.uppercased() + dropFirst()
    }
}
