import WireletSchema

enum ChoiceEmitter {
    static func emit(
        _ choice: WireChoice,
        kotlinName: String,
        modelPackage: String,
        codecPackage: String,
        serializationPackage: String,
        nameTransform: NameTransform,
    ) -> KotlinFile {
        let codecName = "\(kotlinName)Codec"
        let path = codecPackage.replacingOccurrences(of: ".", with: "/") + "/\(codecName).kt"

        // Collect non-primitive referenced types (for `import` lines).
        // Nested-type refs like "Outer.Inner" must be flattened to "Inner" —
        // codecs and model classes are emitted at top level.
        var referenced = Set<String>()
        for c in choice.cases {
            for field in c.payload where KotlinTypeMap.primitive(field.typeText) == nil {
                referenced.insert(nameTransform.apply(to: KotlinTypeMap.simpleName(of: field.typeText)))
            }
        }
        let encodeBranches = choice.cases.enumerated().map { idx, c in
            emitEncodeBranch(case: c, index: idx, kotlinName: kotlinName, nameTransform: nameTransform)
        }.joined(separator: "\n")

        let decodeBranches = choice.cases.enumerated().map { idx, c in
            emitDecodeBranch(case: c, index: idx, kotlinName: kotlinName, nameTransform: nameTransform)
        }.joined(separator: "\n")

        // Build the full imports block. Serialization imports are omitted when
        // BinaryReader/Writer live in the same package as the codec (in scope).
        var importLines = ["import \(modelPackage).\(kotlinName)"]
        importLines += referenced.sorted().map { "import \(modelPackage).\($0)" }
        if serializationPackage != codecPackage {
            importLines.append("import \(serializationPackage).BinaryReader")
            importLines.append("import \(serializationPackage).BinaryWriter")
        }
        let allImports = importLines.joined(separator: "\n")

        let content = """
        // Auto-generated by emit-kotlin-codecs. DO NOT EDIT.
        package \(codecPackage)

        \(allImports)

        public object \(codecName) {
            fun encode(value: \(kotlinName)): ByteArray {
                val w = BinaryWriter()
                encodePayload(value, w)
                return w.toByteArray()
            }

            fun encodePayload(value: \(kotlinName), w: BinaryWriter) {
                when (value) {
        \(encodeBranches)
                }
            }

            fun decode(data: ByteArray): \(kotlinName) {
                val r = BinaryReader(data)
                return decodePayload(r)
            }

            fun decodePayload(r: BinaryReader): \(kotlinName) {
                return when (val disc = r.readU8().toInt()) {
        \(decodeBranches)
                    else -> throw IllegalArgumentException(
                        "Unknown \(kotlinName) discriminator: $disc",
                    )
                }
            }
        }

        """

        return KotlinFile(relativePath: path, content: content)
    }

    private static func propName(for field: PayloadField, at index: Int) -> String {
        field.label ?? "arg\(index)"
    }

    private static func emitEncodeBranch(
        case c: WireChoiceCase,
        index: Int,
        kotlinName: String,
        nameTransform: NameTransform,
    ) -> String {
        let subtype = "\(kotlinName).\(c.name.capitalizedFirst)"
        var lines: [String] = []
        lines.append("            is \(subtype) -> {")
        lines.append("                w.writeU8(\(index)u)")
        for (i, field) in c.payload.enumerated() {
            let prop = propName(for: field, at: i)
            let propAccess = "value.\(prop)"
            if let primitive = KotlinTypeMap.primitive(field.typeText) {
                lines.append("                " + primitive.write(propAccess))
            } else {
                let codecName = nameTransform.apply(to: KotlinTypeMap.simpleName(of: field.typeText)) + "Codec"
                lines.append("                \(codecName).encodePayload(\(propAccess), w)")
            }
        }
        lines.append("            }")
        return lines.joined(separator: "\n")
    }

    private static func emitDecodeBranch(
        case c: WireChoiceCase,
        index: Int,
        kotlinName: String,
        nameTransform: NameTransform,
    ) -> String {
        let subtype = "\(kotlinName).\(c.name.capitalizedFirst)"
        if c.payload.isEmpty {
            return "                    \(index) -> \(subtype)"
        }
        var lines: [String] = []
        lines.append("                    \(index) -> \(subtype)(")
        for (i, field) in c.payload.enumerated() {
            let prop = propName(for: field, at: i)
            if let primitive = KotlinTypeMap.primitive(field.typeText) {
                lines.append("                        \(prop) = \(primitive.read),")
            } else {
                let codecName = nameTransform.apply(to: KotlinTypeMap.simpleName(of: field.typeText)) + "Codec"
                lines.append("                        \(prop) = \(codecName).decodePayload(r),")
            }
        }
        lines.append("                    )")
        return lines.joined(separator: "\n")
    }
}

extension String {
    fileprivate var capitalizedFirst: String {
        guard let first else { return self }
        return first.uppercased() + dropFirst()
    }
}
