import WireletSchema

enum EnumEmitter {
    static func emit(
        _ rawEnum: WireRawEnum,
        kotlinName: String,
        modelPackage: String,
        codecPackage: String,
        serializationPackage: String,
    ) -> KotlinFile {
        let codecName = "\(kotlinName)Codec"
        let path = codecPackage.replacingOccurrences(of: ".", with: "/") + "/\(codecName).kt"

        // Omit the serialization imports when BinaryReader/Writer live in
        // the same package as the codec (they are automatically in scope).
        let serializationImports = serializationPackage == codecPackage ? "" : """

        import \(serializationPackage).BinaryReader
        import \(serializationPackage).BinaryWriter
        """

        let content = """
        // Auto-generated by emit-wirelet-kotlin. DO NOT EDIT.
        package \(codecPackage)

        import \(modelPackage).\(kotlinName)\(serializationImports)

        public object \(codecName) {
            fun encode(value: \(kotlinName)): ByteArray {
                val w = BinaryWriter()
                encodePayload(value, w)
                return w.toByteArray()
            }

            fun encodePayload(value: \(kotlinName), w: BinaryWriter) {
                w.writeU8(value.ordinal.toUByte())
            }

            fun decode(data: ByteArray): \(kotlinName) {
                val r = BinaryReader(data)
                return decodePayload(r)
            }

            fun decodePayload(r: BinaryReader): \(kotlinName) {
                val disc = r.readU8().toInt()
                val values = \(kotlinName).entries
                if (disc < 0 || disc >= values.size) {
                    throw IllegalArgumentException(
                        "Unknown \(kotlinName) ordinal: $disc",
                    )
                }
                return values[disc]
            }
        }

        """

        return KotlinFile(relativePath: path, content: content)
    }
}
