import WireletSchema

enum EnumEmitter {
    /// Emits a Kotlin codec for a `@WireFormatEnum` raw-value enum.
    ///
    /// The Swift macro forwards encoding to the raw type's
    /// `encodePayload(into:)`. For the integer raws this is a varint;
    /// raw-string is varint-prefixed UTF-8 bytes. The Kotlin emitter
    /// targets integer raws (the only kind exercised by current
    /// fixtures) and encodes the case's declaration-order index (which
    /// matches `rawValue` for the canonical
    /// `enum: UInt8 { case a, b, c }` shape).
    ///
    /// `WIRE_TYPE` is `WireType.VARINT` so parent codecs that reference
    /// this enum as a field type get the correct tag wire-type.
    static func emit(
        _ rawEnum: WireRawEnum,
        kotlinName: String,
        modelPackage: String,
        codecPackage: String,
        serializationPackage: String,
    ) -> KotlinFile {
        let codecName = "\(kotlinName)Codec"
        let path = codecPackage.replacingOccurrences(of: ".", with: "/") + "/\(codecName).kt"

        let serializationImports = serializationPackage == codecPackage ? "" : """

        import \(serializationPackage).BinaryReader
        import \(serializationPackage).BinaryWriter
        import \(serializationPackage).WireFormatException
        import \(serializationPackage).WireType
        """

        let content = """
        // Auto-generated by emit-wirelet-kotlin. DO NOT EDIT.
        package \(codecPackage)

        import \(modelPackage).\(kotlinName)\(serializationImports)

        public object \(codecName) {
            val WIRE_TYPE: WireType = WireType.VARINT

            fun encode(value: \(kotlinName)): ByteArray {
                val w = BinaryWriter()
                encodePayload(value, w)
                return w.toByteArray()
            }

            fun encodePayload(value: \(kotlinName), w: BinaryWriter) {
                w.writeVarint(value.ordinal.toLong())
            }

            fun decode(data: ByteArray): \(kotlinName) {
                val r = BinaryReader(data)
                return decodePayload(r)
            }

            fun decodePayload(r: BinaryReader): \(kotlinName) {
                val disc = r.readVarint().toInt()
                val values = \(kotlinName).entries
                if (disc < 0 || disc >= values.size) {
                    throw WireFormatException.InvalidCount(disc)
                }
                return values[disc]
            }
        }

        """

        return KotlinFile(relativePath: path, content: content)
    }
}
