import WireletSchema

/// Emits the Kotlin model declaration (`data class` / `sealed class` /
/// `enum class`) for a wire-format type. Optional companion to the codec
/// emitters — gated by `KotlinCodegenConfig.emitModels`.
///
/// Cross-package imports: collected by walking every referenced type
/// and resolving each through `PackageResolver`. A reference whose model
/// package differs from the host's gets an explicit `import`; same-package
/// references stay unqualified.
enum ModelEmitter {
    static func emitStruct(
        _ wireStruct: WireStruct,
        kotlinName: String,
        modelPackage: String,
        nameTransform: NameTransform,
        resolver: PackageResolver,
    ) -> KotlinFile {
        let path = modelPackage.replacingOccurrences(of: ".", with: "/") + "/\(kotlinName).kt"

        var referenced = Set<String>()
        for field in wireStruct.fields {
            collectReferenced(typeText: field.wrappedTypeText, into: &referenced, transform: nameTransform)
        }
        referenced.remove(kotlinName)
        let importLines = makeImportLines(
            referenced: referenced,
            hostPackage: modelPackage,
            resolver: resolver,
            nameTransform: nameTransform,
        )

        let fieldLines = wireStruct.fields.map { field -> String in
            let baseType = KotlinTypeMap.kotlinType(of: field.wrappedTypeText, nameTransform: nameTransform)
            let typeText = field.isOptional ? "\(baseType)? = null" : baseType
            return "    val \(field.name): \(typeText),"
        }

        let importsBlock = importLines.isEmpty ? "" : "\n" + importLines.joined(separator: "\n") + "\n"
        let body = wireStruct.fields.isEmpty ? "" : "\n" + fieldLines.joined(separator: "\n") + "\n"

        let content = """
        // Auto-generated by emit-wirelet-kotlin. DO NOT EDIT.
        package \(modelPackage)
        \(importsBlock)
        public data class \(kotlinName)(\(body))

        """

        return KotlinFile(relativePath: path, content: content)
    }

    static func emitChoice(
        _ choice: WireChoice,
        kotlinName: String,
        modelPackage: String,
        nameTransform: NameTransform,
        resolver: PackageResolver,
    ) -> KotlinFile {
        let path = modelPackage.replacingOccurrences(of: ".", with: "/") + "/\(kotlinName).kt"

        var referenced = Set<String>()
        for c in choice.cases {
            for field in c.payload {
                collectReferenced(typeText: field.typeText, into: &referenced, transform: nameTransform)
            }
        }
        referenced.remove(kotlinName)
        let importLines = makeImportLines(
            referenced: referenced,
            hostPackage: modelPackage,
            resolver: resolver,
            nameTransform: nameTransform,
        )

        let caseLines = choice.cases.map { c -> String in
            let subname = c.name.upperFirst
            if c.payload.isEmpty {
                return "    public data object \(subname) : \(kotlinName)()"
            }
            let params = c.payload.enumerated().map { i, field -> String in
                let prop = field.label ?? "arg\(i)"
                let kt = KotlinTypeMap.kotlinType(of: field.typeText, nameTransform: nameTransform)
                return "val \(prop): \(kt)"
            }.joined(separator: ", ")
            return "    public data class \(subname)(\(params)) : \(kotlinName)()"
        }

        let importsBlock = importLines.isEmpty ? "" : "\n" + importLines.joined(separator: "\n") + "\n"
        let body = caseLines.isEmpty ? "" : "\n" + caseLines.joined(separator: "\n") + "\n"

        let content = """
        // Auto-generated by emit-wirelet-kotlin. DO NOT EDIT.
        package \(modelPackage)
        \(importsBlock)
        public sealed class \(kotlinName) {\(body)}

        """

        return KotlinFile(relativePath: path, content: content)
    }

    static func emitEnum(
        _ rawEnum: WireRawEnum,
        kotlinName: String,
        modelPackage: String,
    ) -> KotlinFile {
        let path = modelPackage.replacingOccurrences(of: ".", with: "/") + "/\(kotlinName).kt"
        let cases = rawEnum.cases.map { "    \($0.kotlinEnumCase)," }.joined(separator: "\n")
        let body = cases.isEmpty ? "" : "\n\(cases)\n"

        let content = """
        // Auto-generated by emit-wirelet-kotlin. DO NOT EDIT.
        package \(modelPackage)

        public enum class \(kotlinName) {\(body)}

        """

        return KotlinFile(relativePath: path, content: content)
    }

    // MARK: - helpers

    private static func collectReferenced(
        typeText: String,
        into out: inout Set<String>,
        transform: NameTransform,
    ) {
        if KotlinTypeMap.primitive(typeText) != nil { return }
        if let elem = KotlinTypeMap.arrayElementType(typeText) {
            collectReferenced(typeText: elem, into: &out, transform: transform)
            return
        }
        if let (k, v) = KotlinTypeMap.dictionaryTypes(of: typeText) {
            collectReferenced(typeText: k, into: &out, transform: transform)
            collectReferenced(typeText: v, into: &out, transform: transform)
            return
        }
        out.insert(KotlinTypeMap.simpleName(of: typeText))
    }

    /// Produces `import <pkg>.<KotlinName>` for every referenced type whose
    /// resolved model package differs from `hostPackage`. Same-package
    /// references are dropped (Kotlin resolves them implicitly).
    private static func makeImportLines(
        referenced: Set<String>,
        hostPackage: String,
        resolver: PackageResolver,
        nameTransform: NameTransform,
    ) -> [String] {
        var lines: [String] = []
        for swiftName in referenced.sorted() {
            let kotlinName = nameTransform.apply(to: swiftName)
            switch resolver.resolve(swiftName: swiftName, target: .auto) {
            case .skip:
                continue
            case let .emit(modelPkg, _, _, _) where modelPkg == hostPackage:
                continue
            case let .emit(modelPkg, _, _, _):
                lines.append("import \(modelPkg).\(kotlinName)")
            }
        }
        return lines
    }
}

extension String {
    fileprivate var upperFirst: String {
        guard let first else { return self }
        return first.uppercased() + dropFirst()
    }

    /// Kotlin enum cases conventionally use the original Swift case name
    /// verbatim (camelCase / PascalCase preserved). Sufficient for v1
    /// emission — codegen does not attempt to enforce SCREAMING_SNAKE_CASE.
    fileprivate var kotlinEnumCase: String {
        self
    }
}
