import WireletSchema

enum StructEmitter {
    /// Emits a Kotlin codec object for a `@WireFormat`-annotated Swift
    /// struct using the TLV wire format (matches Swift `@WireFormat`
    /// macro emission, Task 2.6).
    ///
    /// Generated layout per codec:
    /// * `WIRE_TYPE` — `WireType.LENGTH_DELIMITED`, used by parent codecs
    ///   that need the field's tag wire-type.
    /// * `encode(value)` — top-level: wraps payload in a varint length
    ///   prefix (mirrors Swift `encodeToData()` for a `@WireFormat` struct).
    /// * `encodePayload(value, w)` — writes raw per-field TLV records into
    ///   `w` (no outer length prefix). Used by parent codecs that already
    ///   wrote the field tag.
    /// * `decode(data)` — reads the length-prefixed top-level encoding and
    ///   parses it.
    /// * `decodePayload(r)` — reads TLV fields from `r` until EOF, then
    ///   builds the value, throwing on missing required fields.
    static func emit(
        _ wireStruct: WireStruct,
        kotlinName: String,
        modelPackage: String,
        codecPackage: String,
        serializationPackage: String,
        nameTransform: NameTransform,
    ) -> KotlinFile {
        let codecName = "\(kotlinName)Codec"
        let path = codecPackage.replacingOccurrences(of: ".", with: "/") + "/\(codecName).kt"

        // Lines below are pre-indented with their target leading
        // whitespace; we only need to join + insert into the template.
        let encodeLines = wireStruct.fields.flatMap { field in
            emitFieldEncode(field: field, transform: nameTransform)
        }
        let encodeBody = encodeLines.map { "        \($0)" }.joined(separator: "\n")

        let decodeLocals = wireStruct.fields.map { field in
            let kotlinType = KotlinTypeMap.kotlinType(of: field.wrappedTypeText, nameTransform: nameTransform)
            return "        var _\(field.name): \(kotlinType)? = null"
        }
        let decodeLocalsBody = decodeLocals.joined(separator: "\n")

        let decodeCases = wireStruct.fields.map { field in
            let readExpr = decodeExpr(typeText: field.wrappedTypeText, readerName: "r", transform: nameTransform)
            return "                \(field.tag) -> _\(field.name) = \(readExpr)"
        }
        let decodeCasesBody = decodeCases.joined(separator: "\n")

        let constructorArgs = wireStruct.fields.map { field in
            if field.isOptional {
                return "            \(field.name) = _\(field.name),"
            }
            let wt = wireTypeRef(for: field.wrappedTypeText, transform: nameTransform)
            return "            \(field.name) = _\(field.name) ?: throw WireFormatException.UnknownTag(\(field.tag), \(wt)),"
        }
        let constructorBody = constructorArgs.joined(separator: "\n")

        // Collect imports.
        var referenced = Set<String>()
        var usesDictionary = false
        for field in wireStruct.fields {
            collectReferenced(typeText: field.wrappedTypeText, into: &referenced, transform: nameTransform)
            if containsDictionary(typeText: field.wrappedTypeText) {
                usesDictionary = true
            }
        }
        referenced.remove(kotlinName)

        var importLines = ["import \(modelPackage).\(kotlinName)"]
        importLines += referenced.sorted().map { "import \(modelPackage).\($0)" }
        if serializationPackage != codecPackage {
            importLines.append("import \(serializationPackage).BinaryReader")
            importLines.append("import \(serializationPackage).BinaryWriter")
            importLines.append("import \(serializationPackage).WireFormatException")
            importLines.append("import \(serializationPackage).WireType")
            if usesDictionary {
                importLines.append("import \(serializationPackage).ByteArrayLexComparator")
            }
        }
        let allImports = importLines.joined(separator: "\n")

        // Assemble the function bodies with their internal `\n`s where
        // needed; the multi-line string literal handles the rest of the
        // indentation.
        let encodeBodyBlock = encodeBody.isEmpty ? "" : encodeBody + "\n"
        let localsBlock = decodeLocalsBody.isEmpty ? "" : decodeLocalsBody + "\n"
        let casesBlock = decodeCasesBody.isEmpty ? "" : decodeCasesBody + "\n"
        let constructorBlock = constructorBody.isEmpty ? "" : constructorBody + "\n"

        let content = """
        // Auto-generated by emit-wirelet-kotlin. DO NOT EDIT.
        package \(codecPackage)

        \(allImports)

        public object \(codecName) {
            val WIRE_TYPE: WireType = WireType.LENGTH_DELIMITED

            fun encode(value: \(kotlinName)): ByteArray {
                val w = BinaryWriter()
                w.writeLengthPrefixed { encodePayload(value, this) }
                return w.toByteArray()
            }

            fun encodePayload(value: \(kotlinName), w: BinaryWriter) {
        \(encodeBodyBlock)    }

            fun decode(data: ByteArray): \(kotlinName) {
                val r = BinaryReader(data)
                return r.readLengthPrefixed { decodePayload(it) }
            }

            fun decodePayload(r: BinaryReader): \(kotlinName) {
        \(localsBlock)        while (r.remaining > 0) {
                    val (tag, wt) = r.readTag()
                    when (tag) {
        \(casesBlock)                else -> r.skipUnknownField(wt)
                    }
                }
                return \(kotlinName)(
        \(constructorBlock)        )
            }
        }

        """

        return KotlinFile(relativePath: path, content: content)
    }

    /// Emits encode lines for one struct field. Required fields produce
    /// `writeTag` + payload write. Optional fields wrap them in a
    /// `?.let { ... }` guard so a nil value writes nothing.
    private static func emitFieldEncode(field: WireField, transform: NameTransform) -> [String] {
        let core = field.wrappedTypeText
        let wt = wireTypeRef(for: core, transform: transform)

        if field.isOptional {
            var lines = ["value.\(field.name)?.let { v ->"]
            lines.append("    w.writeTag(\(field.tag), \(wt))")
            for ln in payloadWrite(typeText: core, valueExpr: "v", writerName: "w", transform: transform) {
                lines.append("    \(ln)")
            }
            lines.append("}")
            return lines
        }
        var lines = ["w.writeTag(\(field.tag), \(wt))"]
        lines.append(contentsOf: payloadWrite(
            typeText: core,
            valueExpr: "value.\(field.name)",
            writerName: "w",
            transform: transform,
        ))
        return lines
    }

    /// Returns one or more Kotlin lines that write the raw payload of a
    /// value of `typeText` (no tag, no outer length-prefix wrap — though
    /// the payload itself may include its own length prefix where the
    /// type requires one, e.g. String / Data / Array / Dictionary).
    static func payloadWrite(
        typeText: String,
        valueExpr: String,
        writerName: String,
        transform: NameTransform,
    ) -> [String] {
        if let primitive = KotlinTypeMap.primitive(typeText) {
            return [primitive.writePayload(valueExpr, writerName)]
        }
        if let elem = KotlinTypeMap.arrayElementType(typeText) {
            return arrayWrite(elemType: elem, valueExpr: valueExpr, writerName: writerName, transform: transform)
        }
        if let (k, v) = KotlinTypeMap.dictionaryTypes(of: typeText) {
            return dictionaryWrite(keyType: k, valueType: v, valueExpr: valueExpr, writerName: writerName, transform: transform)
        }
        let codec = transform.apply(to: KotlinTypeMap.simpleName(of: typeText)) + "Codec"
        // A nested user type frames itself per its own wire type, mirroring
        // the Swift macro's `value.encode(into:)`: a length-delimited type
        // (struct / choice) gets a length prefix the parent decoder can slice
        // by tag, while a scalar type — a `@WireFormatEnum`, whose `WIRE_TYPE`
        // is `VARINT` — is written bare, exactly as the Swift side emits it.
        // Branch on the codec's `WIRE_TYPE` constant so a nested enum field
        // stays byte-compatible with Swift (a bare varint, not length-prefixed).
        return [
            "if (\(codec).WIRE_TYPE == WireType.LENGTH_DELIMITED) "
                + "\(writerName).writeLengthPrefixed { \(codec).encodePayload(\(valueExpr), this) } "
                + "else \(codec).encodePayload(\(valueExpr), \(writerName))",
        ]
    }

    /// Returns a Kotlin expression that reads a value of `typeText` from
    /// `readerName`'s payload, advancing the cursor.
    static func decodeExpr(
        typeText: String,
        readerName: String,
        transform: NameTransform,
    ) -> String {
        if let primitive = KotlinTypeMap.primitive(typeText) {
            return primitive.readPayload(readerName)
        }
        if let elem = KotlinTypeMap.arrayElementType(typeText) {
            return arrayReadExpr(elemType: elem, readerName: readerName, transform: transform)
        }
        if let (k, v) = KotlinTypeMap.dictionaryTypes(of: typeText) {
            return dictionaryReadExpr(keyType: k, valueType: v, readerName: readerName, transform: transform)
        }
        let codec = transform.apply(to: KotlinTypeMap.simpleName(of: typeText)) + "Codec"
        // Symmetric with `payloadWrite`: slice a length-delimited record
        // before decoding its payload; read a scalar type (e.g. a nested
        // `@WireFormatEnum`, `WIRE_TYPE == VARINT`) directly.
        return "(if (\(codec).WIRE_TYPE == WireType.LENGTH_DELIMITED) "
            + "\(readerName).readLengthPrefixed { \(codec).decodePayload(it) } "
            + "else \(codec).decodePayload(\(readerName)))"
    }

    /// Returns the `WireType.<NAME>` reference to use in a `writeTag` call
    /// for a value of `typeText`. Primitives map directly; arrays /
    /// dictionaries are `LENGTH_DELIMITED`; user types defer to the
    /// referenced codec's `WIRE_TYPE` constant.
    static func wireTypeRef(for typeText: String, transform: NameTransform) -> String {
        if let primitive = KotlinTypeMap.primitive(typeText) {
            return primitive.wireType
        }
        if KotlinTypeMap.arrayElementType(typeText) != nil
            || KotlinTypeMap.dictionaryTypes(of: typeText) != nil
        {
            return "WireType.LENGTH_DELIMITED"
        }
        let codec = transform.apply(to: KotlinTypeMap.simpleName(of: typeText)) + "Codec"
        return "\(codec).WIRE_TYPE"
    }

    // MARK: - Array helpers

    private static func arrayWrite(
        elemType: String,
        valueExpr: String,
        writerName: String,
        transform: NameTransform,
    ) -> [String] {
        var lines: [String] = []
        lines.append("\(writerName).writeLengthPrefixed {")
        let inner = payloadWrite(typeText: elemType, valueExpr: "e", writerName: "this", transform: transform)
        if inner.count == 1 {
            lines.append("    for (e in \(valueExpr)) \(inner[0])")
        } else {
            lines.append("    for (e in \(valueExpr)) {")
            for ln in inner { lines.append("        \(ln)") }
            lines.append("    }")
        }
        lines.append("}")
        return lines
    }

    private static func arrayReadExpr(
        elemType: String,
        readerName: String,
        transform: NameTransform,
    ) -> String {
        let kotlinElem = KotlinTypeMap.kotlinType(of: elemType, nameTransform: transform)
        let readOne = decodeExpr(typeText: elemType, readerName: "it", transform: transform)
        return "\(readerName).readLengthPrefixed { val list = ArrayList<\(kotlinElem)>(); while (it.remaining > 0) list.add(\(readOne)); list }"
    }

    // MARK: - Dictionary helpers

    /// Emits a *canonical* dictionary encode: each entry's key is first
    /// written to a scratch `BinaryWriter`, entries are sorted by their
    /// encoded-key bytes (lexicographic, unsigned-byte comparison via
    /// `ByteArrayLexComparator`), then count + sorted (keyBytes, value)
    /// pairs are emitted. Matches Swift's `Dictionary.encodePayload`
    /// canonicalisation so multi-entry Maps round-trip byte-identically
    /// between Swift and Kotlin. Decode is symmetric (order doesn't
    /// matter when populating the target `MutableMap`).
    private static func dictionaryWrite(
        keyType: String,
        valueType: String,
        valueExpr: String,
        writerName: String,
        transform: NameTransform,
    ) -> [String] {
        let writeKInto = payloadWrite(typeText: keyType, valueExpr: "entry.key", writerName: "kw", transform: transform)
        // Use `entryValue` as the destructured local so we don't shadow
        // the codec's outer `value` parameter (Kotlin emits a warning).
        let writeV = payloadWrite(typeText: valueType, valueExpr: "entryValue", writerName: "this", transform: transform)
        var lines: [String] = []
        lines.append("\(writerName).writeLengthPrefixed {")
        lines.append("    val sortedEntries = (\(valueExpr)).entries.map { entry ->")
        lines.append("        val kw = BinaryWriter()")
        for ln in writeKInto { lines.append("        \(ln)") }
        lines.append("        kw.toByteArray() to entry.value")
        lines.append("    }.sortedWith(compareBy(ByteArrayLexComparator) { it.first })")
        lines.append("    writeVarint(sortedEntries.size.toLong())")
        lines.append("    for ((keyBytes, entryValue) in sortedEntries) {")
        lines.append("        writeBytes(keyBytes)")
        for ln in writeV { lines.append("        \(ln)") }
        lines.append("    }")
        lines.append("}")
        return lines
    }

    private static func dictionaryReadExpr(
        keyType: String,
        valueType: String,
        readerName: String,
        transform: NameTransform,
    ) -> String {
        let kk = KotlinTypeMap.kotlinType(of: keyType, nameTransform: transform)
        let vv = KotlinTypeMap.kotlinType(of: valueType, nameTransform: transform)
        // Rename the outer lambda parameter to `dr` (dictionary reader) so
        // that `repeat(count) { ... }`'s implicit `it: Int` doesn't shadow
        // the reader inside the loop body.
        let readK = decodeExpr(typeText: keyType, readerName: "dr", transform: transform)
        let readV = decodeExpr(typeText: valueType, readerName: "dr", transform: transform)
        return "\(readerName).readLengthPrefixed { dr -> val count = dr.readVarint().toInt(); val m = LinkedHashMap<\(kk), \(vv)>(count); repeat(count) { val k = \(readK); val v = \(readV); m[k] = v }; m }"
    }

    // MARK: - Import collection

    private static func collectReferenced(
        typeText: String,
        into out: inout Set<String>,
        transform: NameTransform,
    ) {
        if KotlinTypeMap.primitive(typeText) != nil { return }
        if let elem = KotlinTypeMap.arrayElementType(typeText) {
            collectReferenced(typeText: elem, into: &out, transform: transform)
            return
        }
        if let (k, v) = KotlinTypeMap.dictionaryTypes(of: typeText) {
            collectReferenced(typeText: k, into: &out, transform: transform)
            collectReferenced(typeText: v, into: &out, transform: transform)
            return
        }
        out.insert(transform.apply(to: KotlinTypeMap.simpleName(of: typeText)))
    }

    /// Recursively checks whether `typeText` contains any dictionary type
    /// (the codec then needs to reference `ByteArrayLexComparator` for the
    /// canonical-sort emission and thus import it across packages).
    static func containsDictionary(typeText: String) -> Bool {
        if KotlinTypeMap.primitive(typeText) != nil { return false }
        if let elem = KotlinTypeMap.arrayElementType(typeText) {
            return containsDictionary(typeText: elem)
        }
        if let (k, v) = KotlinTypeMap.dictionaryTypes(of: typeText) {
            _ = k
            _ = v
            return true
        }
        return false
    }
}
