import Foundation
import Testing
import WireletObservableSwiftBridgesEmitter

// MARK: - JNI_OnLoad emission tests

@Suite("JNIOnLoadEmitterTests")
struct JNIOnLoadEmitterTests {
    @Test func renderFileContainsJNIOnLoadFunction() {
        let methods: [NativeMethod] = [
            NativeMethod(name: "nativeNew", signature: "()J", cdeclSymbol: "WireletObservable_CounterVM_new"),
            NativeMethod(name: "nativeRelease", signature: "(J)V", cdeclSymbol: "WireletObservable_CounterVM_release"),
        ]
        let vm = ViewModelRegistration(
            swiftClass: "CounterVM",
            kotlinClassFQN: "io/github/example/CounterVMViewModel",
            nativeMethods: methods,
        )
        let output = JNIOnLoadEmitter.renderFile(viewModels: [vm])
        // Guard wrapping
        #expect(output.contains("#if os(Android)"))
        #expect(output.contains("#endif"))
        // Imports
        #expect(output.contains("import Android"))
        #expect(output.contains("import SwiftJavaJNICore"))
        // JNI_OnLoad function
        #expect(output.contains(#"@_cdecl("JNI_OnLoad")"#))
        #expect(output.contains("public func JNI_OnLoad("))
        // Registers the adopted JVM as the shared instance for JObject.
        #expect(output.contains("JavaVirtualMachine.setShared(JavaVirtualMachine(adoptingJVM: vm))"))
        // FindClass call with the Kotlin FQN
        #expect(output.contains("io/github/example/CounterVMViewModel"))
        // dlsym for each symbol
        #expect(output.contains("WireletObservable_CounterVM_new"))
        #expect(output.contains("WireletObservable_CounterVM_release"))
        // RegisterNatives
        #expect(output.contains("RegisterNatives"))
        // Error handling
        #expect(output.contains("JNI_ERR"))
        #expect(output.contains("JNI_VERSION_1_6"))
        // Generated header
        #expect(output.contains("// Generated by emit-wirelet-observable-swift-bridges."))
    }

    @Test func multipleViewModelsConsolidatedIntoSingleJNIOnLoad() {
        let vm1 = ViewModelRegistration(
            swiftClass: "FooVM",
            kotlinClassFQN: "io/example/FooVMViewModel",
            nativeMethods: [
                NativeMethod(name: "nativeNew", signature: "()J", cdeclSymbol: "WireletObservable_FooVM_new"),
            ],
        )
        let vm2 = ViewModelRegistration(
            swiftClass: "BarVM",
            kotlinClassFQN: "io/example/BarVMViewModel",
            nativeMethods: [
                NativeMethod(name: "nativeNew", signature: "()J", cdeclSymbol: "WireletObservable_BarVM_new"),
            ],
        )
        let output = JNIOnLoadEmitter.renderFile(viewModels: [vm1, vm2])
        // Only ONE JNI_OnLoad function
        let jniOnLoadCount = output.components(separatedBy: #"@_cdecl("JNI_OnLoad")"#).count - 1
        #expect(jniOnLoadCount == 1, "Expected exactly one @_cdecl(JNI_OnLoad), got \(jniOnLoadCount)")
        // Both classes registered
        #expect(output.contains("io/example/FooVMViewModel"))
        #expect(output.contains("io/example/BarVMViewModel"))
        #expect(output.contains("WireletObservable_FooVM_new"))
        #expect(output.contains("WireletObservable_BarVM_new"))
    }

    @Test func emitWithJNIConfigProducesJNIOnLoadFile() throws {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("jni-emit-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tempDir) }

        // Write a minimal Swift source fixture.
        let source = """
        import WireletObservable
        @WireletObservable
        @Observable
        public final class CounterVM {
            public var count: Int32 = 0
        }
        """
        let sourceURL = tempDir.appendingPathComponent("CounterVM.swift")
        try source.write(to: sourceURL, atomically: true, encoding: .utf8)

        let methods = [NativeMethod(
            name: "nativeNew", signature: "()J",
            cdeclSymbol: "WireletObservable_CounterVM_new",
        )]
        let config = JNIRegistrationConfig(viewModels: [
            ViewModelRegistration(
                swiftClass: "CounterVM",
                kotlinClassFQN: "io/github/example/CounterVMViewModel",
                nativeMethods: methods,
            ),
        ])

        let results = try SwiftBridgesEmitter().emit(sources: [sourceURL], jniConfig: config)
        // Expect the bridge file + the JNI_OnLoad file
        #expect(results.count == 2, "Expected 2 output files (bridge + JNI_OnLoad), got \(results.count)")
        let names = results.map(\.name)
        #expect(names.contains("CounterVM+JNIBridges.swift"))
        #expect(names.contains("__WireletObservableJNI_OnLoad.swift"))
        // JNI_OnLoad file must contain the function
        let jniFile = try #require(results.first(where: { $0.name == "__WireletObservableJNI_OnLoad.swift" }))
        #expect(jniFile.content.contains(#"@_cdecl("JNI_OnLoad")"#))
        #expect(jniFile.content.contains("WireletObservable_CounterVM_new"))
    }

    @Test func emitWithoutJNIConfigDoesNotProduceJNIOnLoadFile() throws {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("jni-no-config-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tempDir) }

        let source = """
        import WireletObservable
        @WireletObservable
        @Observable
        public final class CounterVM {
            public var count: Int32 = 0
        }
        """
        let sourceURL = tempDir.appendingPathComponent("CounterVM.swift")
        try source.write(to: sourceURL, atomically: true, encoding: .utf8)

        let results = try SwiftBridgesEmitter().emit(sources: [sourceURL])
        // Only the bridge file — no JNI_OnLoad
        #expect(results.count == 1)
        #expect(results[0].name == "CounterVM+JNIBridges.swift")
        let hasJNIOnLoad = results.contains(where: { $0.name == "__WireletObservableJNI_OnLoad.swift" })
        #expect(!hasJNIOnLoad)
    }

    @Test func emitWithEmptyJNIConfigDoesNotProduceJNIOnLoadFile() throws {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("jni-empty-config-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tempDir) }

        let source = """
        import WireletObservable
        @WireletObservable
        @Observable
        public final class CounterVM {
            public var count: Int32 = 0
        }
        """
        let sourceURL = tempDir.appendingPathComponent("CounterVM.swift")
        try source.write(to: sourceURL, atomically: true, encoding: .utf8)

        // Config with no view models should not produce a JNI_OnLoad file.
        let config = JNIRegistrationConfig(viewModels: [])
        let results = try SwiftBridgesEmitter().emit(sources: [sourceURL], jniConfig: config)
        #expect(results.count == 1)
        let hasJNIOnLoad = results.contains(where: { $0.name == "__WireletObservableJNI_OnLoad.swift" })
        #expect(!hasJNIOnLoad)
    }
}
