import Foundation
import Testing
import WireletObservableSwiftBridgesEmitter

// MARK: - Golden-file tests for SwiftBridgesEmitter

/// These tests verify the shape of the generated `.swift` content by running
/// `SwiftBridgesEmitter.emit(sources:)` against in-memory fixture files written
/// to a temporary directory.

// MARK: - JNI_OnLoad emission tests

@Suite("JNIOnLoadEmitterTests")
struct JNIOnLoadEmitterTests {

    @Test func renderFileContainsJNIOnLoadFunction() {
        let methods: [NativeMethod] = [
            NativeMethod(name: "nativeNew", signature: "()J", cdeclSymbol: "WireletObservable_CounterVM_new"),
            NativeMethod(name: "nativeRelease", signature: "(J)V", cdeclSymbol: "WireletObservable_CounterVM_release"),
        ]
        let vm = ViewModelRegistration(
            swiftClass: "CounterVM",
            kotlinClassFQN: "io/github/example/CounterVMViewModel",
            nativeMethods: methods
        )
        let output = JNIOnLoadEmitter.renderFile(viewModels: [vm])
        // Guard wrapping
        #expect(output.contains("#if os(Android)"))
        #expect(output.contains("#endif"))
        // Imports
        #expect(output.contains("import Android"))
        #expect(output.contains("import CWireletJNI"))
        // JNI_OnLoad function
        #expect(output.contains(#"@_cdecl("JNI_OnLoad")"#))
        #expect(output.contains("public func JNI_OnLoad("))
        // FindClass call with the Kotlin FQN
        #expect(output.contains("io/github/example/CounterVMViewModel"))
        // dlsym for each symbol
        #expect(output.contains("WireletObservable_CounterVM_new"))
        #expect(output.contains("WireletObservable_CounterVM_release"))
        // RegisterNatives
        #expect(output.contains("RegisterNatives"))
        // Error handling
        #expect(output.contains("JNI_ERR"))
        #expect(output.contains("JNI_VERSION_1_6"))
        // Generated header
        #expect(output.contains("// Generated by emit-wirelet-observable-swift-bridges."))
    }

    @Test func multipleViewModelsConsolidatedIntoSingleJNIOnLoad() {
        let vm1 = ViewModelRegistration(
            swiftClass: "FooVM",
            kotlinClassFQN: "io/example/FooVMViewModel",
            nativeMethods: [
                NativeMethod(name: "nativeNew", signature: "()J", cdeclSymbol: "WireletObservable_FooVM_new"),
            ]
        )
        let vm2 = ViewModelRegistration(
            swiftClass: "BarVM",
            kotlinClassFQN: "io/example/BarVMViewModel",
            nativeMethods: [
                NativeMethod(name: "nativeNew", signature: "()J", cdeclSymbol: "WireletObservable_BarVM_new"),
            ]
        )
        let output = JNIOnLoadEmitter.renderFile(viewModels: [vm1, vm2])
        // Only ONE JNI_OnLoad function
        let jniOnLoadCount = output.components(separatedBy: #"@_cdecl("JNI_OnLoad")"#).count - 1
        #expect(jniOnLoadCount == 1, "Expected exactly one @_cdecl(JNI_OnLoad), got \(jniOnLoadCount)")
        // Both classes registered
        #expect(output.contains("io/example/FooVMViewModel"))
        #expect(output.contains("io/example/BarVMViewModel"))
        #expect(output.contains("WireletObservable_FooVM_new"))
        #expect(output.contains("WireletObservable_BarVM_new"))
    }

    @Test func emitWithJNIConfigProducesJNIOnLoadFile() throws {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("jni-emit-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tempDir) }

        // Write a minimal Swift source fixture.
        let source = """
        import WireletObservable
        @WireletObservable
        @Observable
        public final class CounterVM {
            public var count: Int32 = 0
        }
        """
        let sourceURL = tempDir.appendingPathComponent("CounterVM.swift")
        try source.write(to: sourceURL, atomically: true, encoding: .utf8)

        let methods = [NativeMethod(
            name: "nativeNew", signature: "()J",
            cdeclSymbol: "WireletObservable_CounterVM_new"
        )]
        let config = JNIRegistrationConfig(viewModels: [
            ViewModelRegistration(
                swiftClass: "CounterVM",
                kotlinClassFQN: "io/github/example/CounterVMViewModel",
                nativeMethods: methods
            )
        ])

        let results = try SwiftBridgesEmitter().emit(sources: [sourceURL], jniConfig: config)
        // Expect the bridge file + the JNI_OnLoad file
        #expect(results.count == 2, "Expected 2 output files (bridge + JNI_OnLoad), got \(results.count)")
        let names = results.map(\.name)
        #expect(names.contains("CounterVM+JNIBridges.swift"))
        #expect(names.contains("__WireletObservableJNI_OnLoad.swift"))
        // JNI_OnLoad file must contain the function
        let jniFile = results.first(where: { $0.name == "__WireletObservableJNI_OnLoad.swift" })!
        #expect(jniFile.content.contains(#"@_cdecl("JNI_OnLoad")"#))
        #expect(jniFile.content.contains("WireletObservable_CounterVM_new"))
    }

    @Test func emitWithoutJNIConfigDoesNotProduceJNIOnLoadFile() throws {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("jni-no-config-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tempDir) }

        let source = """
        import WireletObservable
        @WireletObservable
        @Observable
        public final class CounterVM {
            public var count: Int32 = 0
        }
        """
        let sourceURL = tempDir.appendingPathComponent("CounterVM.swift")
        try source.write(to: sourceURL, atomically: true, encoding: .utf8)

        let results = try SwiftBridgesEmitter().emit(sources: [sourceURL])
        // Only the bridge file — no JNI_OnLoad
        #expect(results.count == 1)
        #expect(results[0].name == "CounterVM+JNIBridges.swift")
        let hasJNIOnLoad = results.contains(where: { $0.name == "__WireletObservableJNI_OnLoad.swift" })
        #expect(!hasJNIOnLoad)
    }

    @Test func emitWithEmptyJNIConfigDoesNotProduceJNIOnLoadFile() throws {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("jni-empty-config-test-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tempDir) }

        let source = """
        import WireletObservable
        @WireletObservable
        @Observable
        public final class CounterVM {
            public var count: Int32 = 0
        }
        """
        let sourceURL = tempDir.appendingPathComponent("CounterVM.swift")
        try source.write(to: sourceURL, atomically: true, encoding: .utf8)

        // Config with no view models should not produce a JNI_OnLoad file.
        let config = JNIRegistrationConfig(viewModels: [])
        let results = try SwiftBridgesEmitter().emit(sources: [sourceURL], jniConfig: config)
        #expect(results.count == 1)
        let hasJNIOnLoad = results.contains(where: { $0.name == "__WireletObservableJNI_OnLoad.swift" })
        #expect(!hasJNIOnLoad)
    }
}

@Suite("SwiftBridgesEmitterTests")
struct SwiftBridgesEmitterTests {

    // MARK: - Helpers

    private func writeTmp(name: String, content: String) throws -> URL {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent("emitter-tests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appendingPathComponent(name)
        try content.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    // MARK: - Primitive properties

    @Test func primitiveAndBoolProperties() throws {
        let source = """
        import Observation
        import WireletObservable
        @WireletObservable
        @Observable
        public final class CounterVM {
            public var count: Int32 = 0
            public var active: Bool = false
        }
        """
        let url = try writeTmp(name: "CounterVM.swift", content: source)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.count == 1)
        let (name, content) = results[0]
        #expect(name == "CounterVM+JNIBridges.swift")
        // File header
        #expect(content.contains("// Generated by emit-wirelet-observable-swift-bridges."))
        #expect(content.contains("#if os(Android)"))
        // Track bridges
        #expect(content.contains(#"@_cdecl("WireletObservable_CounterVM_count_track")"#))
        #expect(content.contains(#"@_cdecl("WireletObservable_CounterVM_active_track")"#))
        #expect(content.contains("-> jint {"))
        #expect(content.contains("-> jboolean {"))
        #expect(content.contains("jboolean(snapshot ? 1 : 0)"))
        // Constructor / destructor
        #expect(content.contains(#"@_cdecl("WireletObservable_CounterVM_new")"#))
        #expect(content.contains(#"@_cdecl("WireletObservable_CounterVM_release")"#))
        // Setter bridges
        #expect(content.contains(#"@_cdecl("WireletObservable_CounterVM_count_set")"#))
        #expect(content.contains(#"@_cdecl("WireletObservable_CounterVM_active_set")"#))
        // Global (not static) functions
        #expect(!content.contains("static func"))
        // Wrapped in #if os(Android)
        #expect(content.contains("#endif"))
    }

    // MARK: - String property

    @Test func stringProperty() throws {
        let source = """
        import Observation
        import WireletObservable
        @WireletObservable
        @Observable
        public final class LabelVM {
            public var label: String = ""
        }
        """
        let url = try writeTmp(name: "LabelVM.swift", content: source)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.count == 1)
        let (_, content) = results[0]
        #expect(content.contains(#"@_cdecl("WireletObservable_LabelVM_label_track")"#))
        #expect(content.contains("-> jstring?"))
        #expect(content.contains("NewStringUTF"))
        #expect(content.contains(#"@_cdecl("WireletObservable_LabelVM_label_set")"#))
        #expect(content.contains("GetStringUTFChars"))
    }

    // MARK: - WireFormat array property + @WireletExpose methods (golden: TodoListVM)

    @Test func todoListVMGolden() throws {
        let source = """
        import Observation
        import WireletObservable
        @WireletObservable
        @Observable
        public final class TodoListVM {
            public var items: [TodoItem] = []
            public var filter: String = ""
            public var totalCount: Int32 = 0
            public init() {}
            @WireletExpose
            public func add(_ item: TodoItem) {}
            @WireletExpose
            public func clear() {}
        }
        """
        let url = try writeTmp(name: "TodoListVM.swift", content: source)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.count == 1)
        let (name, content) = results[0]
        #expect(name == "TodoListVM+JNIBridges.swift")
        // Track bridges
        #expect(content.contains(#"WireletObservable_TodoListVM_items_track"#))
        #expect(content.contains(#"WireletObservable_TodoListVM_filter_track"#))
        #expect(content.contains(#"WireletObservable_TodoListVM_totalCount_track"#))
        // Setter bridges
        #expect(content.contains(#"WireletObservable_TodoListVM_items_set"#))
        #expect(content.contains(#"WireletObservable_TodoListVM_filter_set"#))
        #expect(content.contains(#"WireletObservable_TodoListVM_totalCount_set"#))
        // Constructor / destructor
        #expect(content.contains(#"WireletObservable_TodoListVM_new"#))
        #expect(content.contains(#"WireletObservable_TodoListVM_release"#))
        // Invoke bridges
        #expect(content.contains(#"WireletObservable_TodoListVM_add_invoke"#))
        #expect(content.contains(#"WireletObservable_TodoListVM_clear_invoke"#))
        // Array setter uses WireFormatReader
        #expect(content.contains("WireFormatReader"))
        #expect(content.contains("encodeArray"))
        // Zero-arg invoke does not take arg0
        let clearBlock = content.components(separatedBy: "clear_invoke").last ?? ""
        #expect(!clearBlock.contains("arg0"))
        // One-arg invoke decodes from jbyteArray
        #expect(content.contains("_ arg0: jbyteArray?"))
    }

    // MARK: - Optional properties

    @Test func optionalStringProperty() throws {
        let source = """
        import Observation
        import WireletObservable
        @WireletObservable
        @Observable
        public final class MaybeVM {
            public var maybe: String? = nil
        }
        """
        let url = try writeTmp(name: "MaybeVM.swift", content: source)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.count == 1)
        let (_, content) = results[0]
        #expect(content.contains(#"WireletObservable_MaybeVM_maybe_track"#))
        #expect(content.contains("guard let value = snapshot else { return nil }"))
        #expect(content.contains(#"WireletObservable_MaybeVM_maybe_set"#))
        #expect(content.contains("me.maybe = nil"))
    }

    // MARK: - Non-@WireletObservable file produces no output

    @Test func nonAnnotatedFileProducesNoResults() throws {
        let source = """
        import Observation
        @Observable
        public final class PlainVM {
            public var x: Int32 = 0
        }
        """
        let url = try writeTmp(name: "PlainVM.swift", content: source)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.isEmpty)
    }

    // MARK: - Non-swift file is ignored

    @Test func nonSwiftFileIgnored() throws {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("ignore.txt")
        try "hello".write(to: url, atomically: true, encoding: .utf8)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.isEmpty)
    }

    // MARK: - let property emits track but no setter

    @Test func letPropertyEmitsTrackNotSetter() throws {
        let source = """
        import Observation
        import WireletObservable
        @WireletObservable
        @Observable
        public final class ReadonlyVM {
            public let value: Int32 = 0
        }
        """
        let url = try writeTmp(name: "ReadonlyVM.swift", content: source)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.count == 1)
        let (_, content) = results[0]
        #expect(content.contains(#"WireletObservable_ReadonlyVM_value_track"#))
        #expect(!content.contains(#"WireletObservable_ReadonlyVM_value_set"#))
    }

    // MARK: - Multi-arg invoke bridge

    @Test func multiArgInvokeBridge() throws {
        let source = """
        import Observation
        import WireletObservable

        @WireletObservable
        @Observable
        public final class Demo {
            @WireletExpose
            public func setDone(_ id: Int32, _ done: Bool) {}
        }
        """
        let url = try writeTmp(name: "Demo.swift", content: source)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        let bridges = results.first(where: { $0.name.hasSuffix("Demo+JNIBridges.swift") })!.content

        #expect(bridges.contains("@_cdecl(\"WireletObservable_Demo_setDone_invoke\")"))
        #expect(bridges.contains("public func __Demo_setDone_invoke_jni("))
        #expect(bridges.contains("_ arg0: jint"))
        #expect(bridges.contains("_ arg1: jboolean"))
        #expect(bridges.contains("let decoded0 = Int32(arg0)"))
        #expect(bridges.contains("let decoded1 = (arg1 != 0)"))
        #expect(bridges.contains("me.setDone(decoded0, decoded1)"))
    }

    // MARK: - Global function names are class-prefixed (no collision risk)

    @Test func globalFunctionNamesArePrefixedWithClassName() throws {
        let source = """
        import Observation
        import WireletObservable
        @WireletObservable
        @Observable
        public final class FooVM {
            public var x: Int32 = 0
        }
        """
        let url = try writeTmp(name: "FooVM.swift", content: source)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.count == 1)
        let (_, content) = results[0]
        // The Swift function symbol must be class-prefixed to avoid collisions
        // when multiple @WireletObservable classes exist in the same module.
        #expect(content.contains("public func __FooVM_x_track_jni("))
        #expect(content.contains("public func __FooVM_x_set_jni("))
        #expect(content.contains("public func __FooVM_new_jni("))
        #expect(content.contains("public func __FooVM_release_jni("))
    }
}
