import Foundation
import Testing
import WireletObservableSwiftBridgesEmitter

// MARK: - Golden-file tests for SwiftBridgesEmitter

/// These tests verify the shape of the generated `.swift` content by running
/// `SwiftBridgesEmitter.emit(sources:)` against in-memory fixture files written
/// to a temporary directory.

@Suite("SwiftBridgesEmitterTests")
struct SwiftBridgesEmitterTests {

    // MARK: - Helpers

    private func writeTmp(name: String, content: String) throws -> URL {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent("emitter-tests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appendingPathComponent(name)
        try content.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    // MARK: - Primitive properties

    @Test func primitiveAndBoolProperties() throws {
        let source = """
        import Observation
        import WireletObservable
        @WireletObservable
        @Observable
        public final class CounterVM {
            public var count: Int32 = 0
            public var active: Bool = false
        }
        """
        let url = try writeTmp(name: "CounterVM.swift", content: source)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.count == 1)
        let (name, content) = results[0]
        #expect(name == "CounterVM+JNIBridges.swift")
        // File header
        #expect(content.contains("// Generated by emit-wirelet-observable-swift-bridges."))
        #expect(content.contains("#if os(Android)"))
        // Track bridges
        #expect(content.contains(#"@_cdecl("WireletObservable_CounterVM_count_track")"#))
        #expect(content.contains(#"@_cdecl("WireletObservable_CounterVM_active_track")"#))
        #expect(content.contains("-> jint {"))
        #expect(content.contains("-> jboolean {"))
        #expect(content.contains("jboolean(snapshot ? 1 : 0)"))
        // Constructor / destructor
        #expect(content.contains(#"@_cdecl("WireletObservable_CounterVM_new")"#))
        #expect(content.contains(#"@_cdecl("WireletObservable_CounterVM_release")"#))
        // Setter bridges
        #expect(content.contains(#"@_cdecl("WireletObservable_CounterVM_count_set")"#))
        #expect(content.contains(#"@_cdecl("WireletObservable_CounterVM_active_set")"#))
        // Global (not static) functions
        #expect(!content.contains("static func"))
        // Wrapped in #if os(Android)
        #expect(content.contains("#endif"))
    }

    // MARK: - String property

    @Test func stringProperty() throws {
        let source = """
        import Observation
        import WireletObservable
        @WireletObservable
        @Observable
        public final class LabelVM {
            public var label: String = ""
        }
        """
        let url = try writeTmp(name: "LabelVM.swift", content: source)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.count == 1)
        let (_, content) = results[0]
        #expect(content.contains(#"@_cdecl("WireletObservable_LabelVM_label_track")"#))
        #expect(content.contains("-> jstring?"))
        #expect(content.contains("NewStringUTF"))
        #expect(content.contains(#"@_cdecl("WireletObservable_LabelVM_label_set")"#))
        #expect(content.contains("GetStringUTFChars"))
    }

    // MARK: - WireFormat array property + @WireletExpose methods (golden: TodoListVM)

    @Test func todoListVMGolden() throws {
        let source = """
        import Observation
        import WireletObservable
        @WireletObservable
        @Observable
        public final class TodoListVM {
            public var items: [TodoItem] = []
            public var filter: String = ""
            public var totalCount: Int32 = 0
            public init() {}
            @WireletExpose
            public func add(_ item: TodoItem) {}
            @WireletExpose
            public func clear() {}
        }
        """
        let url = try writeTmp(name: "TodoListVM.swift", content: source)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.count == 1)
        let (name, content) = results[0]
        #expect(name == "TodoListVM+JNIBridges.swift")
        // Track bridges
        #expect(content.contains(#"WireletObservable_TodoListVM_items_track"#))
        #expect(content.contains(#"WireletObservable_TodoListVM_filter_track"#))
        #expect(content.contains(#"WireletObservable_TodoListVM_totalCount_track"#))
        // Setter bridges
        #expect(content.contains(#"WireletObservable_TodoListVM_items_set"#))
        #expect(content.contains(#"WireletObservable_TodoListVM_filter_set"#))
        #expect(content.contains(#"WireletObservable_TodoListVM_totalCount_set"#))
        // Constructor / destructor
        #expect(content.contains(#"WireletObservable_TodoListVM_new"#))
        #expect(content.contains(#"WireletObservable_TodoListVM_release"#))
        // Invoke bridges
        #expect(content.contains(#"WireletObservable_TodoListVM_add_invoke"#))
        #expect(content.contains(#"WireletObservable_TodoListVM_clear_invoke"#))
        // Array setter uses WireFormatReader
        #expect(content.contains("WireFormatReader"))
        #expect(content.contains("encodeArray"))
        // Zero-arg invoke does not take arg0
        let clearBlock = content.components(separatedBy: "clear_invoke").last ?? ""
        #expect(!clearBlock.contains("arg0"))
        // One-arg invoke decodes from jbyteArray
        #expect(content.contains("_ arg0: jbyteArray?"))
    }

    // MARK: - Optional properties

    @Test func optionalStringProperty() throws {
        let source = """
        import Observation
        import WireletObservable
        @WireletObservable
        @Observable
        public final class MaybeVM {
            public var maybe: String? = nil
        }
        """
        let url = try writeTmp(name: "MaybeVM.swift", content: source)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.count == 1)
        let (_, content) = results[0]
        #expect(content.contains(#"WireletObservable_MaybeVM_maybe_track"#))
        #expect(content.contains("guard let value = snapshot else { return nil }"))
        #expect(content.contains(#"WireletObservable_MaybeVM_maybe_set"#))
        #expect(content.contains("me.maybe = nil"))
    }

    // MARK: - Non-@WireletObservable file produces no output

    @Test func nonAnnotatedFileProducesNoResults() throws {
        let source = """
        import Observation
        @Observable
        public final class PlainVM {
            public var x: Int32 = 0
        }
        """
        let url = try writeTmp(name: "PlainVM.swift", content: source)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.isEmpty)
    }

    // MARK: - Non-swift file is ignored

    @Test func nonSwiftFileIgnored() throws {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("ignore.txt")
        try "hello".write(to: url, atomically: true, encoding: .utf8)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.isEmpty)
    }

    // MARK: - let property emits track but no setter

    @Test func letPropertyEmitsTrackNotSetter() throws {
        let source = """
        import Observation
        import WireletObservable
        @WireletObservable
        @Observable
        public final class ReadonlyVM {
            public let value: Int32 = 0
        }
        """
        let url = try writeTmp(name: "ReadonlyVM.swift", content: source)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.count == 1)
        let (_, content) = results[0]
        #expect(content.contains(#"WireletObservable_ReadonlyVM_value_track"#))
        #expect(!content.contains(#"WireletObservable_ReadonlyVM_value_set"#))
    }

    // MARK: - Global function names are class-prefixed (no collision risk)

    @Test func globalFunctionNamesArePrefixedWithClassName() throws {
        let source = """
        import Observation
        import WireletObservable
        @WireletObservable
        @Observable
        public final class FooVM {
            public var x: Int32 = 0
        }
        """
        let url = try writeTmp(name: "FooVM.swift", content: source)
        let results = try SwiftBridgesEmitter().emit(sources: [url])
        #expect(results.count == 1)
        let (_, content) = results[0]
        // The Swift function symbol must be class-prefixed to avoid collisions
        // when multiple @WireletObservable classes exist in the same module.
        #expect(content.contains("public func __FooVM_x_track_jni("))
        #expect(content.contains("public func __FooVM_x_set_jni("))
        #expect(content.contains("public func __FooVM_new_jni("))
        #expect(content.contains("public func __FooVM_release_jni("))
    }
}
