import WireletKotlinEmitter    // KotlinFile
import WireletProvidedSchema   // ProvidedService, ProvidedMethod, ProvidedParameter

/// Renders one `<Service>.kt` file per `@WireletProvided` protocol.
/// The file contains both the friendly `interface` and the
/// `<Service>NativeAdapter` class (v1 colocates them; `adapterPackage`
/// in config is reserved for a future split-file layout).
enum AdapterEmitter {
    // MARK: - Entry point

    /// - Throws: `ProvidedKotlinEmitterError` if a parameter or return type
    ///   is unsupported (e.g. optionals in v1).
    static func emit(
        service: ProvidedService,
        config: ProvidedCodegenConfig
    ) throws -> KotlinFile {
        let path = config.interfacePackage.replacingOccurrences(of: ".", with: "/")
            + "/\(service.name).kt"

        // Render each method's interface line + adapter line + collect imports.
        var allImports: Set<String> = []
        var interfaceLines: [String] = []
        var adapterLines: [String] = []

        for method in service.methods {
            let (iface, adapter, imports) = try renderMethod(
                method: method, service: service, config: config
            )
            interfaceLines.append("    \(iface)")
            adapterLines.append(adapter)
            allImports.formUnion(imports)
        }

        let importsBlock = allImports.sorted().map { "import \($0)" }.joined(separator: "\n")

        let interfaceBody = interfaceLines.joined(separator: "\n")
        let adapterBody = adapterLines.map { "    \($0)" }.joined(separator: "\n\n")

        let content = """
        // Auto-generated by emit-wirelet-provided. DO NOT EDIT.
        package \(config.interfacePackage)

        \(importsBlock)

        interface \(service.name) {
        \(interfaceBody)
        }

        // v1: adapter colocated with interface (adapterPackage reserved for future split).
        class \(service.name)NativeAdapter(private val impl: \(service.name)) {
        \(adapterBody)
        }

        """
        return KotlinFile(relativePath: path, content: content)
    }

    // MARK: - Method rendering

    /// Returns (interface line, adapter method block, imports).
    private static func renderMethod(
        method: ProvidedMethod,
        service: ProvidedService,
        config: ProvidedCodegenConfig
    ) throws -> (interfaceLine: String, adapterMethod: String, imports: Set<String>) {
        var paramInfos: [(pname: String, info: ProvidedKotlinTypeMap.TypeInfo)] = []
        var allImports: Set<String> = []

        for param in method.parameters {
            let pname = chooseName(param: param)
            let info = try ProvidedKotlinTypeMap.typeInfo(
                forTypeText: param.typeText,
                service: service.name,
                method: method.name,
                config: config
            )
            paramInfos.append((pname, info))
            allImports.formUnion(info.imports)
        }

        // --- Interface line (uses friendly param names) ---
        let friendlyParams = paramInfos.map { "\($0.pname): \($0.info.friendlyType)" }
            .joined(separator: ", ")
        let interfaceLine: String
        if let returnType = method.returnTypeText {
            let retInfo = try ProvidedKotlinTypeMap.typeInfo(
                forTypeText: returnType,
                service: service.name,
                method: method.name,
                config: config
            )
            allImports.formUnion(retInfo.imports)
            interfaceLine = "fun \(method.name)(\(friendlyParams)): \(retInfo.friendlyType)"
        } else {
            interfaceLine = "fun \(method.name)(\(friendlyParams))"
        }

        // --- Adapter wire method ---
        // For ByteArray wire params the semantic name (`item`) belongs to the
        // friendly interface; on the wire side `bytes` better describes the
        // content, and matches the hand-written `TodoStore.kt` golden.
        let wireParamPairs: [(wireName: String, wireType: String, decodeExpr: String)] =
            paramInfos.map { pname, info in
                if info.wireType == "ByteArray" {
                    return ("bytes", info.wireType, info.decode("bytes"))
                }
                return (pname, info.wireType, info.decode(pname))
            }
        let wireParams = wireParamPairs.map { "\($0.wireName): \($0.wireType)" }
            .joined(separator: ", ")
        let decodedArgs = wireParamPairs.map(\.decodeExpr)
            .joined(separator: ", ")
        let implCall = "impl.\(method.name)(\(decodedArgs))"

        let adapterMethod: String
        if let returnType = method.returnTypeText {
            let retInfo = try ProvidedKotlinTypeMap.typeInfo(
                forTypeText: returnType,
                service: service.name,
                method: method.name,
                config: config
            )
            let encoded = retInfo.encode(implCall)
            adapterMethod = "fun \(method.name)Wire(\(wireParams)): \(retInfo.wireType) = \(encoded)"
        } else {
            adapterMethod = "fun \(method.name)Wire(\(wireParams)) { \(implCall) }"
        }

        return (interfaceLine, adapterMethod, allImports)
    }

    // MARK: - Naming

    /// Chooses the Kotlin parameter name for a `ProvidedParameter`.
    /// When the external label is `_`, uses the internal name (if present).
    private static func chooseName(param: ProvidedParameter) -> String {
        if param.label != "_" { return param.label }
        if let inner = param.internalName { return inner }
        return param.label  // fallback: bare `_` (unusual)
    }
}
