import WireletKotlinEmitter
import WireletObservableSchema

enum ViewModelEmitter {
    /// Renders one `<KotlinName>ViewModel.kt` file for `vm`. The Kotlin
    /// class name is `<NameTransform.apply(vm.name)>ViewModel`. The file
    /// lands at `viewModelPackage / KotlinName.kt`.
    static func emit(
        _ vm: ObservableViewModel,
        config: ObservableCodegenConfig
    ) -> KotlinFile {
        let kotlinBase = config.nameTransform.apply(to: vm.name)
        let className = "\(kotlinBase)ViewModel"
        let path = config.viewModelPackage.replacingOccurrences(of: ".", with: "/")
            + "/\(className).kt"

        let plans: [(ObservableProperty, ObservableKotlinTypeMap.Plan)] =
            vm.properties.map { ($0, ObservableKotlinTypeMap.plan(for: $0, config: config)) }

        let imports = collectImports(vm: vm, plans: plans, config: config)
        let importsBlock = imports.sorted().map { "import \($0)" }.joined(separator: "\n")

        let stateFlowMembers = plans.map { prop, plan in
            stateFlowMember(property: prop, plan: plan)
        }.joined(separator: "\n\n")

        let trackHelpers = plans.map { prop, plan in
            trackHelper(property: prop, plan: plan)
        }.joined(separator: "\n\n")

        let externalTrackDecls = plans.map { prop, plan in
            "    private external fun \(nativeTrackFnName(prop))(self: Long, onChange: Runnable): \(plan.nativeTrackReturn)"
        }.joined(separator: "\n")

        let externalReleaseDecl = "    private external fun nativeRelease(self: Long)"

        let content = """
        // Auto-generated by emit-wirelet-observable. DO NOT EDIT.
        package \(config.viewModelPackage)

        \(importsBlock)

        class \(className) internal constructor(
            private val nativePtr: Long
        ) : ViewModel() {

        \(joinBlock(stateFlowMembers))\(joinBlock(trackHelpers))    override fun onCleared() {
                nativeRelease(nativePtr)
                super.onCleared()
            }

        \(joinBlock(externalTrackDecls, trailing: false))\(externalReleaseDecl)

            companion object {
                init { System.loadLibrary("\(config.libraryName)") }

                fun create(): \(className) =
                    \(className)(nativeNew())

                @JvmStatic
                private external fun nativeNew(): Long
            }
        }

        """
        return KotlinFile(relativePath: path, content: content)
    }

    // MARK: - Imports

    private static func collectImports(
        vm: ObservableViewModel,
        plans: [(ObservableProperty, ObservableKotlinTypeMap.Plan)],
        config: ObservableCodegenConfig
    ) -> Set<String> {
        var imports: Set<String> = [
            "androidx.lifecycle.ViewModel",
        ]
        if !plans.isEmpty {
            imports.formUnion([
                "androidx.lifecycle.viewModelScope",
                "kotlinx.coroutines.Dispatchers",
                "kotlinx.coroutines.flow.MutableStateFlow",
                "kotlinx.coroutines.flow.StateFlow",
                "kotlinx.coroutines.flow.asStateFlow",
                "kotlinx.coroutines.launch",
            ])
        }
        for (_, plan) in plans {
            imports.formUnion(plan.extraImports)
        }
        return imports
    }

    // MARK: - Member rendering

    private static func stateFlowMember(
        property: ObservableProperty,
        plan: ObservableKotlinTypeMap.Plan
    ) -> String {
        let initial = "read\(capitalised(property.name))WithTracking()"
        return """
            private val _\(property.name) = MutableStateFlow(\(initial))
            val \(property.name): StateFlow<\(plan.kotlinType)> = _\(property.name).asStateFlow()
        """
    }

    private static func trackHelper(
        property: ObservableProperty,
        plan: ObservableKotlinTypeMap.Plan
    ) -> String {
        let helperName = "read\(capitalised(property.name))WithTracking"
        let nativeFn = nativeTrackFnName(property)
        let nativeCall = "\(nativeFn)(nativePtr, Runnable {\n"
            + "            viewModelScope.launch(Dispatchers.Main) {\n"
            + "                _\(property.name).value = \(helperName)()\n"
            + "            }\n"
            + "        })"
        let decoded = plan.decodeTemplate.replacingOccurrences(of: "$1", with: nativeCall)
        return """
            private fun \(helperName)(): \(plan.kotlinType) =
                \(decoded)
        """
    }

    // MARK: - Naming

    private static func nativeTrackFnName(_ property: ObservableProperty) -> String {
        "native\(capitalised(property.name))Track"
    }

    static func capitalised(_ s: String) -> String {
        guard let first = s.first else { return s }
        return first.uppercased() + s.dropFirst()
    }

    static func joinBlock(_ block: String, trailing: Bool = true) -> String {
        if block.isEmpty { return "" }
        return trailing ? "\(block)\n\n" : "\(block)\n"
    }
}
