import WireletKotlinEmitter
import WireletObservableSchema

enum ViewModelEmitter {
    /// Renders one `<KotlinName>ViewModel.kt` file for `vm`. The Kotlin
    /// class name is `<NameTransform.apply(vm.name)>ViewModel`. The file
    /// lands at `viewModelPackage / KotlinName.kt`.
    static func emit(
        _ vm: ObservableViewModel,
        config: ObservableCodegenConfig
    ) -> KotlinFile {
        let kotlinBase = config.nameTransform.apply(to: vm.name)
        let className = "\(kotlinBase)ViewModel"
        let path = config.viewModelPackage.replacingOccurrences(of: ".", with: "/")
            + "/\(className).kt"

        let plans: [(ObservableProperty, ObservableKotlinTypeMap.Plan)] =
            vm.properties.map { ($0, ObservableKotlinTypeMap.plan(for: $0, config: config)) }

        let methodRenders = vm.methods.compactMap { method in
            methodWrapper(method: method, config: config)
        }
        let methodImports = methodRenders.reduce(into: Set<String>()) { acc, r in
            acc.formUnion(r.extraImports)
        }

        let imports = collectImports(vm: vm, plans: plans, config: config,
                                     extraMethodImports: methodImports)
        let importsBlock = imports.sorted().map { "import \($0)" }.joined(separator: "\n")

        let stateFlowMembers = plans.map { prop, plan in
            stateFlowMember(property: prop, plan: plan)
        }.joined(separator: "\n\n")

        let trackHelpers = plans.map { prop, plan in
            trackHelper(property: prop, plan: plan)
        }.joined(separator: "\n\n")

        let setterWrappers = plans.compactMap { prop, plan in
            setterWrapper(property: prop, plan: plan)
        }.joined(separator: "\n\n")

        let methodWrappers = methodRenders.map(\.publicFn).joined(separator: "\n\n")

        let externalTrackDecls = plans.map { prop, plan in
            "    private external fun \(nativeTrackFnName(prop))(self: Long, onChange: Runnable): \(plan.nativeTrackReturn)"
        }.joined(separator: "\n")

        let setterExternalDecls = plans.compactMap { prop, plan in
            setterExternalDecl(property: prop, plan: plan)
        }.joined(separator: "\n")

        let methodExternalDecls = methodRenders.map(\.externalDecl).joined(separator: "\n")

        let content = """
        // Auto-generated by emit-wirelet-observable. DO NOT EDIT.
        package \(config.viewModelPackage)

        \(importsBlock)

        class \(className) internal constructor(
            private val nativePtr: Long
        ) : ViewModel() {

        \(joinBlock(stateFlowMembers))\(joinBlock(trackHelpers))\(joinBlock(setterWrappers))\(joinBlock(methodWrappers))    override fun onCleared() {
                nativeRelease(nativePtr)
                super.onCleared()
            }

        \(joinBlock(externalTrackDecls, trailing: false))\(joinBlock(setterExternalDecls, trailing: false))\(joinBlock(methodExternalDecls, trailing: false))    private external fun nativeRelease(self: Long)

            companion object {
                init { System.loadLibrary("\(config.libraryName)") }

                fun create(): \(className) =
                    \(className)(nativeNew())

                @JvmStatic
                private external fun nativeNew(): Long
            }
        }

        """
        return KotlinFile(relativePath: path, content: content)
    }

    // MARK: - Imports

    private static func collectImports(
        vm: ObservableViewModel,
        plans: [(ObservableProperty, ObservableKotlinTypeMap.Plan)],
        config: ObservableCodegenConfig,
        extraMethodImports: Set<String>
    ) -> Set<String> {
        var imports: Set<String> = [
            "androidx.lifecycle.ViewModel",
        ]
        if !plans.isEmpty {
            imports.formUnion([
                "androidx.lifecycle.viewModelScope",
                "kotlinx.coroutines.Dispatchers",
                "kotlinx.coroutines.flow.MutableStateFlow",
                "kotlinx.coroutines.flow.StateFlow",
                "kotlinx.coroutines.flow.asStateFlow",
                "kotlinx.coroutines.launch",
            ])
        }
        for (_, plan) in plans {
            imports.formUnion(plan.extraImports)
        }
        imports.formUnion(extraMethodImports)
        return imports
    }

    // MARK: - Setter rendering

    private static func setterWrapper(
        property: ObservableProperty,
        plan: ObservableKotlinTypeMap.Plan
    ) -> String? {
        guard property.isMutable, plan.nativeSetParam != nil,
              let encodeTpl = plan.encodeTemplate
        else { return nil }
        let encoded = encodeTpl.replacingOccurrences(of: "$1", with: "value")
        let nativeFn = "native\(capitalised(property.name))Set"
        return """
            fun update\(capitalised(property.name))(value: \(plan.kotlinType)) {
                \(nativeFn)(nativePtr, \(encoded))
            }
        """
    }

    private static func setterExternalDecl(
        property: ObservableProperty,
        plan: ObservableKotlinTypeMap.Plan
    ) -> String? {
        guard property.isMutable, let nativeParam = plan.nativeSetParam else { return nil }
        let nativeFn = "native\(capitalised(property.name))Set"
        return "    private external fun \(nativeFn)(self: Long, value: \(nativeParam))"
    }

    // MARK: - Method rendering

    private enum ObservableTypeClassifierBridge {
        static func isPrimitive(_ s: String) -> Bool {
            switch s {
            case "Int8", "Int16", "Int32", "Int64",
                 "UInt8", "UInt16", "UInt32", "UInt64",
                 "Bool", "Float", "Double":
                return true
            default:
                return false
            }
        }
    }

    private static func methodWrapper(
        method: ObservableMethod,
        config: ObservableCodegenConfig
    ) -> (publicFn: String, externalDecl: String, extraImports: Set<String>)? {
        switch method.parameters.count {
        case 0:
            let nativeFn = "native\(capitalised(method.name))"
            let publicFn = """
                fun \(method.name)() = \(nativeFn)(nativePtr)
            """
            let external = "    private external fun \(nativeFn)(self: Long)"
            return (publicFn, external, [])
        case 1:
            let param = method.parameters[0]
            let swiftType = param.typeText
            // Only @WireFormat-typed single-arg methods are supported (mirrors
            // the macro's `renderInvoke` rejection of primitive + String —
            // Sources/WireletObservableMacros/WireletObservableMacro.swift:485).
            if ObservableTypeClassifierBridge.isPrimitive(swiftType) || swiftType == "String" {
                return nil
            }
            let codec = config.nameTransform.apply(to: swiftType) + "Codec"
            let kotlinType = config.nameTransform.apply(to: swiftType)
            // Spec line 264: surface the Swift internal parameter name (e.g.
            // `_ item: TodoItem` → `fun add(item:)`) so the Kotlin signature feels
            // natural to consumers. Fall back to the external label when the parameter
            // has only one name (e.g. `func add(item:)`), and to `arg0` only as a
            // safety net.
            let argName: String = {
                if param.label != "_" { return param.label }
                if let internalName = param.internalName { return internalName }
                return "arg0"
            }()
            let nativeFn = "native\(capitalised(method.name))"
            let publicFn = """
                fun \(method.name)(\(argName): \(kotlinType)) =
                    \(nativeFn)(nativePtr, \(codec).encode(\(argName)))
            """
            let external = "    private external fun \(nativeFn)(self: Long, arg0: ByteArray)"
            let imports: Set<String> = [
                "\(config.modelPackage).\(kotlinType)",
                "\(config.codecPackage).\(codec)",
            ]
            return (publicFn, external, imports)
        default:
            // >1 params unsupported (macro layer also rejects).
            return nil
        }
    }

    // MARK: - Member rendering

    private static func stateFlowMember(
        property: ObservableProperty,
        plan: ObservableKotlinTypeMap.Plan
    ) -> String {
        let initial = "read\(capitalised(property.name))WithTracking()"
        return """
            private val _\(property.name) = MutableStateFlow(\(initial))
            val \(property.name): StateFlow<\(plan.kotlinType)> = _\(property.name).asStateFlow()
        """
    }

    private static func trackHelper(
        property: ObservableProperty,
        plan: ObservableKotlinTypeMap.Plan
    ) -> String {
        let helperName = "read\(capitalised(property.name))WithTracking"
        let nativeFn = nativeTrackFnName(property)
        let nativeCall = "\(nativeFn)(nativePtr, Runnable {\n"
            + "            viewModelScope.launch(Dispatchers.Main) {\n"
            + "                _\(property.name).value = \(helperName)()\n"
            + "            }\n"
            + "        })"
        let decoded = plan.decodeTemplate.replacingOccurrences(of: "$1", with: nativeCall)
        return """
            private fun \(helperName)(): \(plan.kotlinType) =
                \(decoded)
        """
    }

    // MARK: - Naming

    private static func nativeTrackFnName(_ property: ObservableProperty) -> String {
        "native\(capitalised(property.name))Track"
    }

    static func capitalised(_ s: String) -> String {
        guard let first = s.first else { return s }
        return first.uppercased() + s.dropFirst()
    }

    static func joinBlock(_ block: String, trailing: Bool = true) -> String {
        if block.isEmpty { return "" }
        return trailing ? "\(block)\n\n" : "\(block)\n"
    }
}
