import WireletKotlinEmitter
import WireletObservableSchema

enum ViewModelEmitter {
    /// Renders one `<KotlinName>ViewModel.kt` file for `vm`. The Kotlin
    /// class name is `<NameTransform.apply(vm.name)>ViewModel`. The file
    /// lands at `viewModelPackage / KotlinName.kt`.
    static func emit(
        _ vm: ObservableViewModel,
        config: ObservableCodegenConfig
    ) -> KotlinFile {
        let kotlinBase = config.nameTransform.apply(to: vm.name)
        let className = "\(kotlinBase)ViewModel"
        let path = config.viewModelPackage.replacingOccurrences(of: ".", with: "/")
            + "/\(className).kt"

        let plans: [(ObservableProperty, ObservableKotlinTypeMap.Plan)] =
            vm.properties.map { ($0, ObservableKotlinTypeMap.plan(for: $0, config: config)) }

        let methodRenders = vm.methods.compactMap { method in
            methodWrapper(method: method, config: config)
        }
        let methodImports = methodRenders.reduce(into: Set<String>()) { acc, r in
            acc.formUnion(r.extraImports)
        }

        let factory = injectedFactory(vm: vm, className: className, config: config)

        let imports = collectImports(vm: vm, plans: plans, config: config,
                                     extraMethodImports: methodImports)
            .union(factory.imports)
        let importsBlock = imports.sorted().map { "import \($0)" }.joined(separator: "\n")

        let stateFlowMembers = plans.map { prop, plan in
            stateFlowMember(property: prop, plan: plan)
        }.joined(separator: "\n\n")

        let trackHelpers = plans.map { prop, plan in
            trackHelper(property: prop, plan: plan)
        }.joined(separator: "\n\n")

        let setterWrappers = plans.compactMap { prop, plan in
            setterWrapper(property: prop, plan: plan)
        }.joined(separator: "\n\n")

        let methodWrappers = methodRenders.map(\.publicFn).joined(separator: "\n\n")

        let externalTrackDecls = plans.map { prop, plan in
            "    private external fun \(nativeTrackFnName(prop))(self: Long, onChange: Runnable): \(plan.nativeTrackReturn)"
        }.joined(separator: "\n")

        let setterExternalDecls = plans.compactMap { prop, plan in
            setterExternalDecl(property: prop, plan: plan)
        }.joined(separator: "\n")

        let methodExternalDecls = methodRenders.map(\.externalDecl).joined(separator: "\n")

        let content = """
        // Auto-generated by emit-wirelet-observable. DO NOT EDIT.
        package \(config.viewModelPackage)

        \(importsBlock)

        class \(className) internal constructor(
            private val nativePtr: Long
        ) : ViewModel() {

        \(joinBlock(stateFlowMembers))\(joinBlock(trackHelpers))\(joinBlock(setterWrappers))\(joinBlock(methodWrappers))    override fun onCleared() {
                nativeRelease(nativePtr)
                super.onCleared()
            }

        \(joinBlock(externalTrackDecls, trailing: false))\(joinBlock(setterExternalDecls, trailing: false))\(joinBlock(methodExternalDecls, trailing: false))    private external fun nativeRelease(self: Long)

            companion object {
                init { System.loadLibrary("\(config.libraryName)") }

        \(factory.body)
            }
        }

        """
        return KotlinFile(relativePath: path, content: content)
    }

    // MARK: - Constructor factory

    /// Renders the companion-object `create(...)` factory + its
    /// `private external fun nativeNew(...)` declaration, plus the imports
    /// for any provided-service adapter types referenced.
    ///
    /// No-arg init (`vm.initParameters` empty): emits today's
    /// `create(): X = X(nativeNew())` + `nativeNew(): Long` unchanged.
    ///
    /// Injected init: each parameter is a `@WireletProvided` service. The
    /// factory takes the friendly service-interface type and wraps it in the
    /// generated `<Service>NativeAdapter` before passing it to `nativeNew`.
    private static func injectedFactory(
        vm: ObservableViewModel,
        className: String,
        config: ObservableCodegenConfig
    ) -> (body: String, imports: Set<String>) {
        guard !vm.initParameters.isEmpty else {
            let body = """
                    fun create(): \(className) =
                        \(className)(nativeNew())

                    @JvmStatic
                    private external fun nativeNew(): Long
            """
            return (body, [])
        }

        var createParams: [String] = []
        var adapterWraps: [String] = []
        var nativeParams: [String] = []
        var imports: Set<String> = []

        for param in vm.initParameters {
            let paramName = factoryParamName(param)
            let serviceType = param.typeText
            let adapterType = "\(serviceType)NativeAdapter"
            createParams.append("\(paramName): \(serviceType)")
            adapterWraps.append("\(adapterType)(\(paramName))")
            nativeParams.append("\(paramName)Adapter: \(adapterType)")
            // Qualify imports by providedAdapterPackage when set. When nil
            // (colocated-package fallback) emit the type names unqualified and
            // add no import — the generated file is expected to live in the
            // same package as the service interface + adapter.
            if let pkg = config.providedAdapterPackage {
                imports.insert("\(pkg).\(serviceType)")
                imports.insert("\(pkg).\(adapterType)")
            }
        }

        let body = """
                fun create(\(createParams.joined(separator: ", "))): \(className) =
                    \(className)(nativeNew(\(adapterWraps.joined(separator: ", "))))

                @JvmStatic
                private external fun nativeNew(\(nativeParams.joined(separator: ", "))): Long
        """
        return (body, imports)
    }

    /// The friendly factory parameter name: the internal name when present,
    /// else the external label, with a leading underscore dropped.
    private static func factoryParamName(_ param: ObservableInitParameter) -> String {
        let name = param.internalName ?? param.label
        return name.hasPrefix("_") ? String(name.dropFirst()) : name
    }

    // MARK: - Imports

    private static func collectImports(
        vm: ObservableViewModel,
        plans: [(ObservableProperty, ObservableKotlinTypeMap.Plan)],
        config: ObservableCodegenConfig,
        extraMethodImports: Set<String>
    ) -> Set<String> {
        var imports: Set<String> = [
            "androidx.lifecycle.ViewModel",
        ]
        if !plans.isEmpty {
            imports.formUnion([
                "androidx.lifecycle.viewModelScope",
                "kotlinx.coroutines.Dispatchers",
                "kotlinx.coroutines.flow.MutableStateFlow",
                "kotlinx.coroutines.flow.StateFlow",
                "kotlinx.coroutines.flow.asStateFlow",
                "kotlinx.coroutines.launch",
            ])
        }
        for (_, plan) in plans {
            imports.formUnion(plan.extraImports)
        }
        imports.formUnion(extraMethodImports)
        return imports
    }

    // MARK: - Setter rendering

    private static func setterWrapper(
        property: ObservableProperty,
        plan: ObservableKotlinTypeMap.Plan
    ) -> String? {
        guard property.isMutable, plan.nativeSetParam != nil,
              let encodeTpl = plan.encodeTemplate
        else { return nil }
        let encoded = encodeTpl.replacingOccurrences(of: "$1", with: "value")
        let nativeFn = "native\(capitalised(property.name))Set"
        return """
            fun update\(capitalised(property.name))(value: \(plan.kotlinType)) {
                \(nativeFn)(nativePtr, \(encoded))
            }
        """
    }

    private static func setterExternalDecl(
        property: ObservableProperty,
        plan: ObservableKotlinTypeMap.Plan
    ) -> String? {
        guard property.isMutable, let nativeParam = plan.nativeSetParam else { return nil }
        let nativeFn = "native\(capitalised(property.name))Set"
        return "    private external fun \(nativeFn)(self: Long, value: \(nativeParam))"
    }

    // MARK: - Method rendering

    private static func methodWrapper(
        method: ObservableMethod,
        config: ObservableCodegenConfig
    ) -> (publicFn: String, externalDecl: String, extraImports: Set<String>)? {
        let nativeFn = "native\(capitalised(method.name))"
        let params = method.parameters

        if params.isEmpty {
            let publicFn = """
                fun \(method.name)() = \(nativeFn)(nativePtr)
            """
            let external = "    private external fun \(nativeFn)(self: Long)"
            return (publicFn, external, [])
        }

        var argDecls: [String] = []
        var nativeArgs: [String] = []
        var externalParams: [String] = ["self: Long"]
        var imports: Set<String> = []

        for (idx, param) in params.enumerated() {
            let publicName = chooseArgName(param: param, idx: idx)
            let info = ObservableKotlinTypeMap.invokeArg(forArgType: param.typeText, config: config)
            argDecls.append("\(publicName): \(info.kotlinType)")
            nativeArgs.append(info.encodeExpr(publicName))
            externalParams.append("arg\(idx): \(info.externalFunType)")
            switch InvokeArgClassifier.classify(param.typeText) {
            case .wireFormat(let t):
                let kt = config.nameTransform.apply(to: t)
                imports.insert("\(config.modelPackage).\(kt)")
                imports.insert("\(config.codecPackage).\(kt)Codec")
            case .optionalWireFormat(let t):
                let kt = config.nameTransform.apply(to: t)
                imports.insert("\(config.modelPackage).\(kt)")
                imports.insert("\(config.codecPackage).\(kt)Codec")
            case .array(let t):
                // Primitive `String` arrays use the runtime's `encodeStrings`
                // (no generated codec); only WireletList needs importing.
                if case .string = InvokeArgClassifier.classify(t) {
                    imports.insert("\(config.runtimePackage).WireletList")
                } else {
                    let kt = config.nameTransform.apply(to: t)
                    imports.insert("\(config.modelPackage).\(kt)")
                    imports.insert("\(config.codecPackage).\(kt)Codec")
                    imports.insert("\(config.runtimePackage).WireletList")
                }
            case .optionalPrimitive:
                imports.insert("\(config.runtimePackage).WireletOptional")
            default:
                break
            }
        }

        let publicFn = """
            fun \(method.name)(\(argDecls.joined(separator: ", "))) =
                \(nativeFn)(nativePtr, \(nativeArgs.joined(separator: ", ")))
        """
        let external = "    private external fun \(nativeFn)(\(externalParams.joined(separator: ", ")))"
        return (publicFn, external, imports)
    }

    private static func chooseArgName(param: ObservableMethodParameter, idx: Int) -> String {
        if param.label != "_" { return param.label }
        if let internalName = param.internalName { return internalName }
        return "arg\(idx)"
    }

    // MARK: - Member rendering

    private static func stateFlowMember(
        property: ObservableProperty,
        plan: ObservableKotlinTypeMap.Plan
    ) -> String {
        let initial = "read\(capitalised(property.name))WithTracking()"
        return """
            private val _\(property.name) = MutableStateFlow(\(initial))
            val \(property.name): StateFlow<\(plan.kotlinType)> = _\(property.name).asStateFlow()
        """
    }

    private static func trackHelper(
        property: ObservableProperty,
        plan: ObservableKotlinTypeMap.Plan
    ) -> String {
        let helperName = "read\(capitalised(property.name))WithTracking"
        let nativeFn = nativeTrackFnName(property)
        let nativeCall = "\(nativeFn)(nativePtr, Runnable {\n"
            + "            viewModelScope.launch(Dispatchers.Main) {\n"
            + "                _\(property.name).value = \(helperName)()\n"
            + "            }\n"
            + "        })"
        let decoded = plan.decodeTemplate.replacingOccurrences(of: "$1", with: nativeCall)
        return """
            private fun \(helperName)(): \(plan.kotlinType) =
                \(decoded)
        """
    }

    // MARK: - Naming

    private static func nativeTrackFnName(_ property: ObservableProperty) -> String {
        "native\(capitalised(property.name))Track"
    }

    static func capitalised(_ s: String) -> String {
        guard let first = s.first else { return s }
        return first.uppercased() + s.dropFirst()
    }

    static func joinBlock(_ block: String, trailing: Bool = true) -> String {
        if block.isEmpty { return "" }
        return trailing ? "\(block)\n\n" : "\(block)\n"
    }
}
