// Cross-language conformance schemas (Task 2.14).
//
// These types are encoded by Swift and decoded by both Swift and Kotlin
// to lock down the wire format. Any change to the macro emission or
// runtime that drifts from the committed fixtures will break the
// conformance tests, forcing a deliberate fixture bump.
//
// The Kotlin side mirrors these with hand-authored data classes
// under `kotlin/conformance-tests/src/main/kotlin/.../model/` and uses
// codecs generated by `emit-wirelet-kotlin` from THIS file.

import Foundation
import Wirelet

@WireFormat
public struct Primitives {
    public var u32: UInt32
    public var i32: Int32
    public var f: Float
    public var d: Double
    public var s: String
    public var b: Bool

    public init(u32: UInt32, i32: Int32, f: Float, d: Double, s: String, b: Bool) {
        self.u32 = u32
        self.i32 = i32
        self.f = f
        self.d = d
        self.s = s
        self.b = b
    }
}

@WireFormat
public struct OptionalHolder {
    public var a: Int32
    public var b: Int32?

    public init(a: Int32, b: Int32?) {
        self.a = a
        self.b = b
    }
}

@WireFormatChoice
public enum ShapeChoice: Equatable {
    case point(Int32, Int32)
    case label(String)
}

// v2 of OptionalHolder for forward-compat. Tags 1, 2 are shared with v1;
// tag 3 (`c`) is new. Decoding v2 bytes with v1's schema must silently
// skip tag 3 via the macro-generated tag-loop + `skipUnknownField`.
@WireFormat
public struct OptionalHolderV2 {
    public var a: Int32
    public var b: Int32?
    public var c: String?

    public init(a: Int32, b: Int32?, c: String?) {
        self.a = a
        self.b = b
        self.c = c
    }
}

// Multi-entry Map fixture (Task 2.10 follow-up). Exercises the
// canonical-key-sort emission in both Swift's Dictionary conformance and
// the Kotlin emitter — proving multi-entry Maps round-trip byte-identically
// across both languages regardless of host iteration order.
@WireFormat
public struct MapHolder {
    public var m: [String: Int32]

    public init(m: [String: Int32]) {
        self.m = m
    }
}
