// Auto-generated by emit-wirelet-kotlin. DO NOT EDIT.
package io.example.audio.serialization

import io.example.audio.model.GMInstrumentFamily

public object GMInstrumentFamilyCodec {
    val WIRE_TYPE: WireType = WireType.VARINT

    fun encode(value: GMInstrumentFamily): ByteArray {
        val w = BinaryWriter()
        encodePayload(value, w)
        return w.toByteArray()
    }

    fun encodePayload(value: GMInstrumentFamily, w: BinaryWriter) {
        w.writeVarint(value.ordinal.toLong())
    }

    fun decode(data: ByteArray): GMInstrumentFamily {
        val r = BinaryReader(data)
        return decodePayload(r)
    }

    fun decodePayload(r: BinaryReader): GMInstrumentFamily {
        val disc = r.readVarint().toInt()
        val values = GMInstrumentFamily.entries
        if (disc < 0 || disc >= values.size) {
            throw WireFormatException.InvalidCount(disc)
        }
        return values[disc]
    }
}
