// Auto-generated by emit-kotlin-codecs. DO NOT EDIT.
package io.example.audio.serialization

import io.example.audio.model.GMInstrumentFamily

public object GMInstrumentFamilyCodec {
    fun encode(value: GMInstrumentFamily): ByteArray {
        val w = BinaryWriter()
        encodePayload(value, w)
        return w.toByteArray()
    }

    fun encodePayload(value: GMInstrumentFamily, w: BinaryWriter) {
        w.writeU8(value.ordinal.toUByte())
    }

    fun decode(data: ByteArray): GMInstrumentFamily {
        val r = BinaryReader(data)
        return decodePayload(r)
    }

    fun decodePayload(r: BinaryReader): GMInstrumentFamily {
        val disc = r.readU8().toInt()
        val values = GMInstrumentFamily.entries
        if (disc < 0 || disc >= values.size) {
            throw IllegalArgumentException(
                "Unknown GMInstrumentFamily ordinal: $disc",
            )
        }
        return values[disc]
    }
}
