// Auto-generated by emit-kotlin-codecs. DO NOT EDIT.
package io.example.audio.serialization

import io.example.audio.model.Point

public object PointCodec {
    fun encode(value: Point): ByteArray {
        val w = BinaryWriter()
        encodePayload(value, w)
        return w.toByteArray()
    }

    fun encodePayload(value: Point, w: BinaryWriter) {
        w.writeI32(value.x)
        w.writeI32(value.y)
    }

    fun decode(data: ByteArray): Point {
        val r = BinaryReader(data)
        return decodePayload(r)
    }

    fun decodePayload(r: BinaryReader): Point {
        val x = r.readI32()
        val y = r.readI32()
        return Point(
            x = x,
            y = y,
        )
    }
}
