// Auto-generated by emit-wirelet-kotlin. DO NOT EDIT.
package io.example.audio.serialization

import io.example.audio.model.ScoreCursor
import io.example.audio.model.ScoreItemID

public object ScoreCursorCodec {
    val WIRE_TYPE: WireType = WireType.LENGTH_DELIMITED

    fun encode(value: ScoreCursor): ByteArray {
        val w = BinaryWriter()
        w.writeLengthPrefixed { encodePayload(value, this) }
        return w.toByteArray()
    }

    fun encodePayload(value: ScoreCursor, w: BinaryWriter) {
        when (value) {
            is ScoreCursor.Item -> {
                w.writeVarint(0L)
                w.writeTag(1, ScoreItemIDCodec.WIRE_TYPE)
                w.writeLengthPrefixed { ScoreItemIDCodec.encodePayload(value.arg0, this) }
            }
            is ScoreCursor.Beat -> {
                w.writeVarint(1L)
                w.writeTag(1, WireType.VARINT)
                w.writeZigZagVarint((value.measureIndex).toLong())
                w.writeTag(2, WireType.VARINT)
                w.writeZigZagVarint((value.tickInMeasure).toLong())
            }
        }
    }

    fun decode(data: ByteArray): ScoreCursor {
        val r = BinaryReader(data)
        return r.readLengthPrefixed { decodePayload(it) }
    }

    fun decodePayload(r: BinaryReader): ScoreCursor {
        val disc = r.readVarint()
        return when (disc) {
            0L -> {
                var _arg0: ScoreItemID? = null
                while (r.remaining > 0) {
                    val (tag, wt) = r.readTag()
                    when (tag) {
                        1 -> _arg0 = r.readLengthPrefixed { ScoreItemIDCodec.decodePayload(it) }
                        else -> r.skipUnknownField(wt)
                    }
                }
                val arg0 = _arg0 ?: throw WireFormatException.UnknownTag(1, ScoreItemIDCodec.WIRE_TYPE)
                ScoreCursor.Item(arg0 = arg0)
            }
            1L -> {
                var _arg0: Int? = null
                var _arg1: Int? = null
                while (r.remaining > 0) {
                    val (tag, wt) = r.readTag()
                    when (tag) {
                        1 -> _arg0 = r.readZigZagVarint().toInt()
                        2 -> _arg1 = r.readZigZagVarint().toInt()
                        else -> r.skipUnknownField(wt)
                    }
                }
                val arg0 = _arg0 ?: throw WireFormatException.UnknownTag(1, WireType.VARINT)
                val arg1 = _arg1 ?: throw WireFormatException.UnknownTag(2, WireType.VARINT)
                ScoreCursor.Beat(measureIndex = arg0, tickInMeasure = arg1)
            }
            else -> throw WireFormatException.UnknownChoiceDiscriminator(disc.toInt())
        }
    }
}
