// Auto-generated by emit-wirelet-kotlin. DO NOT EDIT.
package io.example.audio.serialization

import io.example.audio.model.ScoreCursor
import io.example.audio.model.ScoreItemID

public object ScoreCursorCodec {
    fun encode(value: ScoreCursor): ByteArray {
        val w = BinaryWriter()
        encodePayload(value, w)
        return w.toByteArray()
    }

    fun encodePayload(value: ScoreCursor, w: BinaryWriter) {
        when (value) {
            is ScoreCursor.Item -> {
                w.writeU8(0u)
                ScoreItemIDCodec.encodePayload(value.arg0, w)
            }
            is ScoreCursor.Beat -> {
                w.writeU8(1u)
                w.writeI32(value.measureIndex)
                w.writeI32(value.tickInMeasure)
            }
        }
    }

    fun decode(data: ByteArray): ScoreCursor {
        val r = BinaryReader(data)
        return decodePayload(r)
    }

    fun decodePayload(r: BinaryReader): ScoreCursor {
        return when (val disc = r.readU8().toInt()) {
                    0 -> ScoreCursor.Item(
                        arg0 = ScoreItemIDCodec.decodePayload(r),
                    )
                    1 -> ScoreCursor.Beat(
                        measureIndex = r.readI32(),
                        tickInMeasure = r.readI32(),
                    )
            else -> throw IllegalArgumentException(
                "Unknown ScoreCursor discriminator: $disc",
            )
        }
    }
}
