// Auto-generated by emit-kotlin-codecs. DO NOT EDIT.
package io.example.smufl

import io.example.smufl.SMuFLMetrics
import io.example.smufl.SMuFLMetricsEntry
import io.example.audio.serialization.BinaryReader
import io.example.audio.serialization.BinaryWriter

public object SMuFLMetricsCodec {
    fun encode(value: SMuFLMetrics): ByteArray {
        val w = BinaryWriter()
        encodePayload(value, w)
        return w.toByteArray()
    }

    fun encodePayload(value: SMuFLMetrics, w: BinaryWriter) {
        w.writeU32(value.magic)
        w.writeU32(value.version)
        w.writeF64(value.referenceSize)
        w.writeI32(value.entries.size)
        for (entry in value.entries) SMuFLMetricsEntryCodec.encodePayload(entry, w)
    }

    fun decode(data: ByteArray): SMuFLMetrics {
        val r = BinaryReader(data)
        return decodePayload(r)
    }

    fun decodePayload(r: BinaryReader): SMuFLMetrics {
        val magic = r.readU32()
        val version = r.readU32()
        val referenceSize = r.readF64()
        val count = r.readI32()
        val entries = ArrayList<SMuFLMetricsEntry>(count)
        repeat(count) { entries.add(SMuFLMetricsEntryCodec.decodePayload(r)) }
        return SMuFLMetrics(
            magic = magic,
            version = version,
            referenceSize = referenceSize,
            entries = entries,
        )
    }
}
