// Auto-generated by emit-wirelet-kotlin. DO NOT EDIT.
package io.example.smufl

import io.example.smufl.SMuFLMetrics
import io.example.smufl.SMuFLMetricsEntry
import io.example.audio.serialization.BinaryReader
import io.example.audio.serialization.BinaryWriter
import io.example.audio.serialization.WireFormatException
import io.example.audio.serialization.WireType

public object SMuFLMetricsCodec {
    val WIRE_TYPE: WireType = WireType.LENGTH_DELIMITED

    fun encode(value: SMuFLMetrics): ByteArray {
        val w = BinaryWriter()
        w.writeLengthPrefixed { encodePayload(value, this) }
        return w.toByteArray()
    }

    fun encodePayload(value: SMuFLMetrics, w: BinaryWriter) {
        w.writeTag(1, WireType.VARINT)
        w.writeVarint((value.magic).toLong())
        w.writeTag(2, WireType.VARINT)
        w.writeVarint((value.version).toLong())
        w.writeTag(3, WireType.FIXED64)
        w.writeF64(value.referenceSize)
        w.writeTag(4, WireType.LENGTH_DELIMITED)
        w.writeLengthPrefixed {
            for (e in value.entries) if (SMuFLMetricsEntryCodec.WIRE_TYPE == WireType.LENGTH_DELIMITED) this.writeLengthPrefixed { SMuFLMetricsEntryCodec.encodePayload(e, this) } else SMuFLMetricsEntryCodec.encodePayload(e, this)
        }
    }

    fun decode(data: ByteArray): SMuFLMetrics {
        val r = BinaryReader(data)
        return r.readLengthPrefixed { decodePayload(it) }
    }

    fun decodePayload(r: BinaryReader): SMuFLMetrics {
        var _magic: UInt? = null
        var _version: UInt? = null
        var _referenceSize: Double? = null
        var _entries: List<SMuFLMetricsEntry>? = null
        while (r.remaining > 0) {
            val (tag, wt) = r.readTag()
            when (tag) {
                1 -> _magic = r.readVarint().toUInt()
                2 -> _version = r.readVarint().toUInt()
                3 -> _referenceSize = r.readF64()
                4 -> _entries = r.readLengthPrefixed { val list = ArrayList<SMuFLMetricsEntry>(); while (it.remaining > 0) list.add((if (SMuFLMetricsEntryCodec.WIRE_TYPE == WireType.LENGTH_DELIMITED) it.readLengthPrefixed { SMuFLMetricsEntryCodec.decodePayload(it) } else SMuFLMetricsEntryCodec.decodePayload(it))); list }
                else -> r.skipUnknownField(wt)
            }
        }
        return SMuFLMetrics(
            magic = _magic ?: throw WireFormatException.UnknownTag(1, WireType.VARINT),
            version = _version ?: throw WireFormatException.UnknownTag(2, WireType.VARINT),
            referenceSize = _referenceSize ?: throw WireFormatException.UnknownTag(3, WireType.FIXED64),
            entries = _entries ?: throw WireFormatException.UnknownTag(4, WireType.LENGTH_DELIMITED),
        )
    }
}
