import Testing
import WireletProvidedKotlinEmitter
import WireletProvidedSchema

// MARK: - Shared helpers

private func makeConfig(
    interfacePackage: String = "com.example.iface",
    adapterPackage: String = "com.example.iface",
    modelPackage: String = "com.example.model",
    codecPackage: String = "com.example.codec",
    runtimePackage: String = "io.github.jiyimeta.wirelet.observable",
) -> ProvidedCodegenConfig {
    ProvidedCodegenConfig(
        interfacePackage: interfacePackage,
        adapterPackage: adapterPackage,
        modelPackage: modelPackage,
        codecPackage: codecPackage,
        runtimePackage: runtimePackage,
    )
}

@Suite("ProvidedKotlinEmitterTests")
struct ProvidedKotlinEmitterTests {
    // MARK: - 1. todoStoreGolden

    /// Reproduces the hand-written `TodoStore.kt` golden (minus `InMemoryTodoStore`
    /// and `StoreProbe`, which are app-specific). The emitter's output must
    /// match exactly so Phase 4 can delete the hand-written file.
    @Test func todoStoreGolden() throws {
        let source = """
        import Wirelet
        import WireletProvided

        @WireletProvided
        protocol TodoStore {
            func loadAll() -> [TodoItem]
            func add(_ item: TodoItem)
            func remove(_ id: Int32)
        }
        """
        let schema = ProvidedSchemaParser.parse(source: source, fileName: "TodoStore.swift")
        let config = makeConfig()
        let files = try ProvidedKotlinEmitter(config: config).emit(schema: schema)

        #expect(files.count == 1)
        let file = try #require(files.first)

        // Path reflects interface package.
        #expect(file.relativePath == "com/example/iface/TodoStore.kt")

        let c = file.content

        // Header.
        #expect(c.contains("// Auto-generated by emit-wirelet-provided. DO NOT EDIT."))

        // Package.
        #expect(c.contains("package com.example.iface"))

        // Imports.
        #expect(c.contains("import com.example.model.TodoItem"))
        #expect(c.contains("import com.example.codec.TodoItemCodec"))
        #expect(c.contains("import io.github.jiyimeta.wirelet.observable.WireletList"))

        // Interface shape.
        #expect(c.contains("interface TodoStore {"))
        #expect(c.contains("fun loadAll(): List<TodoItem>"))
        #expect(c.contains("fun add(item: TodoItem)"))
        #expect(c.contains("fun remove(id: Int)"))

        // Adapter class shape.
        #expect(c.contains("class TodoStoreNativeAdapter(private val impl: TodoStore) {"))

        // Adapter wire methods.
        let loadAllWire = "fun loadAllWire(): ByteArray = WireletList.encode("
            + "impl.loadAll(), TodoItemCodec::encodePayload)"
        #expect(c.contains(loadAllWire))
        #expect(c.contains("fun addWire(item: ByteArray) { impl.add(TodoItemCodec.decode(item)) }"))
        #expect(c.contains("fun removeWire(id: Int) { impl.remove(id) }"))
    }

    // MARK: - 2. scalarsAndString

    /// Scalar primitives and String pass through unchanged (no codec, no
    /// ByteArray wrapping). Wire type == friendly type for all of them.
    @Test func scalarsAndString() throws {
        let source = """
        import WireletProvided

        @WireletProvided
        protocol ScalarService {
            func count() -> Int32
            func label() -> String
            func setScale(_ s: Double)
        }
        """
        let schema = ProvidedSchemaParser.parse(source: source, fileName: "ScalarService.swift")
        let config = makeConfig()
        let files = try ProvidedKotlinEmitter(config: config).emit(schema: schema)

        #expect(files.count == 1)
        let c = try #require(files.first).content

        // Interface.
        #expect(c.contains("fun count(): Int"))
        #expect(c.contains("fun label(): String"))
        #expect(c.contains("fun setScale(s: Double)"))

        // Wire methods: primitives / string pass through.
        #expect(c.contains("fun countWire(): Int = impl.count()"))
        #expect(c.contains("fun labelWire(): String = impl.label()"))
        #expect(c.contains("fun setScaleWire(s: Double) { impl.setScale(s) }"))
    }

    // MARK: - 3. optionalThrows

    /// A method that returns an optional type must cause `emit` to throw
    /// `ProvidedKotlinEmitterError` (optionals are deferred to v2).
    @Test func optionalThrows() throws {
        let source = """
        import WireletProvided

        @WireletProvided
        protocol FinderService {
            func find(_ id: Int32) -> TodoItem?
        }
        """
        let schema = ProvidedSchemaParser.parse(source: source, fileName: "FinderService.swift")
        let config = makeConfig()
        #expect(throws: ProvidedKotlinEmitterError.self) {
            _ = try ProvidedKotlinEmitter(config: config).emit(schema: schema)
        }
    }

    // MARK: - 4. multipleByteArgsCompile

    /// A protocol method with two ByteArray-mapped parameters must emit two
    /// DISTINCT wire parameter names (using the friendly param names), so the
    /// generated Kotlin is valid (no duplicate identifier in the same parameter
    /// list).
    @Test func multipleByteArgsCompile() throws {
        let source = """
        import WireletProvided

        @WireletProvided
        protocol MergeService {
            func merge(_ a: TodoItem, _ b: [TodoItem])
        }
        """
        let schema = ProvidedSchemaParser.parse(source: source, fileName: "MergeService.swift")
        let config = makeConfig()
        let files = try ProvidedKotlinEmitter(config: config).emit(schema: schema)

        #expect(files.count == 1)
        let c = try #require(files.first).content

        // Interface: friendly types.
        #expect(c.contains("fun merge(a: TodoItem, b: List<TodoItem>)"))

        // Adapter: both wire params use distinct friendly names, not "bytes".
        #expect(c.contains("fun mergeWire(a: ByteArray, b: ByteArray)"))

        // Body decodes each param from its own named variable.
        #expect(c.contains("impl.merge(TodoItemCodec.decode(a), WireletList.decode(b, TodoItemCodec::decodePayload))"))
    }
}
