import Foundation
import Testing
@testable import WireletKotlinEmitter
import WireletSchema

@Test func doesNotEmitModelsByDefault() throws {
    let schema = Schema(types: [
        .struct(WireStruct(
            name: "Point",
            fields: [
                WireField(name: "x", typeText: "Int32", tag: 1),
                WireField(name: "y", typeText: "Int32", tag: 2),
            ],
            kotlinTarget: .auto,
        )),
    ])
    let config = KotlinCodegenConfig(
        defaultModelPackage: "io.example.model",
        defaultCodecPackage: "io.example.serialization",
    )

    let files = try KotlinEmitter(config: config).emit(schema: schema)

    #expect(files.count == 1)
    #expect(files[0].relativePath == "io/example/serialization/PointCodec.kt")
}

@Test func emitsStructModelDataClass() throws {
    let schema = Schema(types: [
        .struct(WireStruct(
            name: "Point",
            fields: [
                WireField(name: "x", typeText: "Int32", tag: 1),
                WireField(name: "y", typeText: "Int32", tag: 2),
            ],
            kotlinTarget: .auto,
        )),
    ])
    let config = KotlinCodegenConfig(
        defaultModelPackage: "io.example.model",
        defaultCodecPackage: "io.example.serialization",
        emitModels: true,
    )

    let files = try KotlinEmitter(config: config).emit(schema: schema)

    #expect(files.count == 2)
    let model = try #require(files.first { $0.relativePath == "io/example/model/Point.kt" })
    #expect(model.content == """
    // Auto-generated by emit-wirelet-kotlin. DO NOT EDIT.
    package io.example.model

    public data class Point(
        val x: Int,
        val y: Int,
    )

    """)
}

@Test func emitsStructModelWithOptionalFieldDefault() throws {
    let schema = Schema(types: [
        .struct(WireStruct(
            name: "OptionalHolder",
            fields: [
                WireField(name: "a", typeText: "Int32", tag: 1),
                WireField(
                    name: "b",
                    typeText: "Int32?",
                    wrappedTypeText: "Int32",
                    isOptional: true,
                    tag: 2,
                ),
            ],
            kotlinTarget: .auto,
        )),
    ])
    let config = KotlinCodegenConfig(
        defaultModelPackage: "io.example.model",
        defaultCodecPackage: "io.example.serialization",
        emitModels: true,
    )

    let files = try KotlinEmitter(config: config).emit(schema: schema)
    let model = try #require(files.first { $0.relativePath == "io/example/model/OptionalHolder.kt" })
    #expect(model.content.contains("val a: Int,"))
    #expect(model.content.contains("val b: Int? = null,"))
}

@Test func emitsChoiceModelWithSealedClass() throws {
    let schema = Schema(types: [
        .choice(WireChoice(
            name: "ShapeChoice",
            cases: [
                WireChoiceCase(name: "point", payload: [
                    PayloadField(label: nil, typeText: "Int32"),
                    PayloadField(label: nil, typeText: "Int32"),
                ]),
                WireChoiceCase(name: "label", payload: [
                    PayloadField(label: nil, typeText: "String"),
                ]),
                WireChoiceCase(name: "empty", payload: []),
            ],
            kotlinTarget: .auto,
        )),
    ])
    let config = KotlinCodegenConfig(
        defaultModelPackage: "io.example.model",
        defaultCodecPackage: "io.example.serialization",
        emitModels: true,
    )

    let files = try KotlinEmitter(config: config).emit(schema: schema)
    let model = try #require(files.first { $0.relativePath == "io/example/model/ShapeChoice.kt" })
    #expect(model.content == """
    // Auto-generated by emit-wirelet-kotlin. DO NOT EDIT.
    package io.example.model

    public sealed class ShapeChoice {
        public data class Point(val arg0: Int, val arg1: Int) : ShapeChoice()
        public data class Label(val arg0: String) : ShapeChoice()
        public data object Empty : ShapeChoice()
    }

    """)
}

@Test func emitsChoiceModelHonoursPayloadLabels() throws {
    let schema = Schema(types: [
        .choice(WireChoice(
            name: "Tagged",
            cases: [
                WireChoiceCase(name: "named", payload: [
                    PayloadField(label: "id", typeText: "UInt32"),
                    PayloadField(label: "value", typeText: "String"),
                ]),
            ],
            kotlinTarget: .auto,
        )),
    ])
    let config = KotlinCodegenConfig(
        defaultModelPackage: "io.example.model",
        defaultCodecPackage: "io.example.serialization",
        emitModels: true,
    )

    let files = try KotlinEmitter(config: config).emit(schema: schema)
    let model = try #require(files.first { $0.relativePath == "io/example/model/Tagged.kt" })
    #expect(model.content.contains("public data class Named(val id: UInt, val value: String) : Tagged()"))
}

@Test func emitsRawEnumModel() throws {
    let schema = Schema(types: [
        .rawEnum(WireRawEnum(
            name: "Color",
            cases: ["red", "green", "blue"],
            kotlinTarget: .auto,
        )),
    ])
    let config = KotlinCodegenConfig(
        defaultModelPackage: "io.example.model",
        defaultCodecPackage: "io.example.serialization",
        emitModels: true,
    )

    let files = try KotlinEmitter(config: config).emit(schema: schema)
    let model = try #require(files.first { $0.relativePath == "io/example/model/Color.kt" })
    #expect(model.content == """
    // Auto-generated by emit-wirelet-kotlin. DO NOT EDIT.
    package io.example.model

    public enum class Color {
        red,
        green,
        blue,
    }

    """)
}

@Test func structModelImportsCrossPackageReferences() throws {
    let schema = Schema(types: [
        .struct(WireStruct(
            name: "Outer",
            fields: [
                WireField(name: "inner", typeText: "Inner", tag: 1),
            ],
            kotlinTarget: .auto,
        )),
        .struct(WireStruct(
            name: "Inner",
            fields: [
                WireField(name: "v", typeText: "Int32", tag: 1),
            ],
            kotlinTarget: .auto,
        )),
    ])
    let config = KotlinCodegenConfig(
        defaultModelPackage: "io.example.model",
        defaultCodecPackage: "io.example.serialization",
        rules: [
            Rule(pattern: "Inner", modelPackage: "io.example.other"),
        ],
        emitModels: true,
    )

    let files = try KotlinEmitter(config: config).emit(schema: schema)
    let outer = try #require(files.first { $0.relativePath == "io/example/model/Outer.kt" })
    #expect(outer.content.contains("import io.example.other.Inner"))
    let inner = try #require(files.first { $0.relativePath == "io/example/other/Inner.kt" })
    #expect(!inner.content.contains("import"))
}

@Test func structModelOmitsSamePackageImports() throws {
    let schema = Schema(types: [
        .struct(WireStruct(
            name: "Outer",
            fields: [
                WireField(name: "items", typeText: "[Inner]", tag: 1),
            ],
            kotlinTarget: .auto,
        )),
        .struct(WireStruct(
            name: "Inner",
            fields: [
                WireField(name: "v", typeText: "Int32", tag: 1),
            ],
            kotlinTarget: .auto,
        )),
    ])
    let config = KotlinCodegenConfig(
        defaultModelPackage: "io.example.model",
        defaultCodecPackage: "io.example.serialization",
        emitModels: true,
    )

    let files = try KotlinEmitter(config: config).emit(schema: schema)
    let outer = try #require(files.first { $0.relativePath == "io/example/model/Outer.kt" })
    #expect(!outer.content.contains("import io.example.model.Inner"))
    #expect(outer.content.contains("val items: List<Inner>"))
}

@Test func nameTransformAppliesToModelName() throws {
    let schema = Schema(types: [
        .struct(WireStruct(
            name: "PointWire",
            fields: [
                WireField(name: "x", typeText: "Int32", tag: 1),
            ],
            kotlinTarget: .auto,
        )),
    ])
    let config = KotlinCodegenConfig(
        defaultModelPackage: "io.example.model",
        defaultCodecPackage: "io.example.serialization",
        nameTransform: .stripSuffix("Wire"),
        emitModels: true,
    )

    let files = try KotlinEmitter(config: config).emit(schema: schema)
    let model = try #require(files.first { $0.relativePath == "io/example/model/Point.kt" })
    #expect(model.content.contains("public data class Point("))
}

@Test func emitModelsConfigDecodesFromJSON() throws {
    let json = #"""
    {
      "defaultModelPackage": "io.example.model",
      "defaultCodecPackage": "io.example.serialization",
      "emitModels": true
    }
    """#
    let config = try JSONDecoder().decode(KotlinCodegenConfig.self, from: Data(json.utf8))
    #expect(config.emitModels == true)
}

@Test func emitModelsDefaultsToFalseWhenAbsentFromJSON() throws {
    let json = #"""
    {
      "defaultModelPackage": "io.example.model",
      "defaultCodecPackage": "io.example.serialization"
    }
    """#
    let config = try JSONDecoder().decode(KotlinCodegenConfig.self, from: Data(json.utf8))
    #expect(config.emitModels == false)
}
