import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxMacros

/// Diagnostic-only peer macro. Validates that `@WireletObservable` is applied
/// to a `final @Observable` class and that any `@WireletExpose` methods use
/// supported signatures. No Swift code is emitted — the actual `@_cdecl` JNI
/// bridges are generated by the `WireletObservableBridges` SwiftPM build tool
/// plugin via the `EmitWireletObservableSwiftBridges` CLI.
public struct WireletObservableMacro: PeerMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let classDecl = declaration.as(ClassDeclSyntax.self) else {
            context.diagnose(Diagnostic(node: Syntax(node), message: WireletObservableDiagnostic.notAFinalClass))
            return []
        }
        guard hasFinalModifier(classDecl) else {
            context.diagnose(Diagnostic(node: Syntax(classDecl.name), message: WireletObservableDiagnostic.notAFinalClass))
            return []
        }
        guard hasObservableAttribute(classDecl) else {
            context.diagnose(Diagnostic(node: Syntax(classDecl.name), message: WireletObservableDiagnostic.missingObservableAttribute))
            return []
        }

        // Diagnose unsupported @WireletExpose method signatures early, at
        // attribute-application time, so the consumer sees the error in the
        // editor rather than waiting for plugin run time.
        for member in classDecl.memberBlock.members {
            guard let funcDecl = member.decl.as(FunctionDeclSyntax.self) else { continue }
            guard hasWireletExposeAttribute(funcDecl) else { continue }
            let params = funcDecl.signature.parameterClause.parameters
            if params.count > 1 {
                context.diagnose(Diagnostic(
                    node: Syntax(funcDecl.name),
                    message: WireletObservableDiagnostic.unsupportedExposedMethodSignature
                ))
            } else if params.count == 1, let p = params.first {
                let t = p.type.trimmedDescription
                if isPrimitiveType(t) || t == "String" {
                    context.diagnose(Diagnostic(
                        node: Syntax(funcDecl.name),
                        message: WireletObservableDiagnostic.unsupportedExposedMethodSignature
                    ))
                }
            }
        }
        return []
    }

    // MARK: - Helpers

    private static func hasFinalModifier(_ decl: ClassDeclSyntax) -> Bool {
        decl.modifiers.contains { $0.name.tokenKind == .keyword(.final) }
    }

    private static func hasObservableAttribute(_ decl: ClassDeclSyntax) -> Bool {
        decl.attributes.contains { element in
            guard let attribute = element.as(AttributeSyntax.self) else { return false }
            return attribute.attributeName.trimmedDescription == "Observable"
        }
    }

    private static func hasWireletExposeAttribute(_ funcDecl: FunctionDeclSyntax) -> Bool {
        funcDecl.attributes.contains { element in
            guard let attribute = element.as(AttributeSyntax.self) else { return false }
            return attribute.attributeName.trimmedDescription == "WireletExpose"
        }
    }

    private static func isPrimitiveType(_ typeText: String) -> Bool {
        switch typeText {
        case "Int8", "Int16", "Int32", "Int64",
             "UInt8", "UInt16", "UInt32", "UInt64",
             "Bool", "Float", "Double":
            return true
        default:
            return false
        }
    }
}
