import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxMacros

/// Diagnostic-only peer macro. Validates that `@WireletObservable` is applied
/// to a `final @Observable` class and that any `@WireletExpose` methods use
/// supported signatures. No Swift code is emitted — the actual `@_cdecl` JNI
/// bridges are generated by the `WireletObservableBridges` SwiftPM build tool
/// plugin via the `EmitWireletObservableSwiftBridges` CLI.
public struct WireletObservableMacro: PeerMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let classDecl = declaration.as(ClassDeclSyntax.self) else {
            context.diagnose(Diagnostic(node: Syntax(node), message: WireletObservableDiagnostic.notAFinalClass))
            return []
        }
        guard hasFinalModifier(classDecl) else {
            context.diagnose(Diagnostic(node: Syntax(classDecl.name), message: WireletObservableDiagnostic.notAFinalClass))
            return []
        }
        guard hasObservableAttribute(classDecl) else {
            context.diagnose(Diagnostic(node: Syntax(classDecl.name), message: WireletObservableDiagnostic.missingObservableAttribute))
            return []
        }

        // (no per-method diagnostic — the schema parser + classifier
        // downstream accept any arity. Unrepresentable types surface as a
        // compile error in the generated bridge.)
        return []
    }

    // MARK: - Helpers

    private static func hasFinalModifier(_ decl: ClassDeclSyntax) -> Bool {
        decl.modifiers.contains { $0.name.tokenKind == .keyword(.final) }
    }

    private static func hasObservableAttribute(_ decl: ClassDeclSyntax) -> Bool {
        decl.attributes.contains { element in
            guard let attribute = element.as(AttributeSyntax.self) else { return false }
            return attribute.attributeName.trimmedDescription == "Observable"
        }
    }


}
