import Foundation
import WireletObservableSchema  // InvokeArgClassifier, InvokeArgKind
import WireletProvidedSchema    // ProvidedSchema, ProvidedService, ProvidedMethod, ProvidedParameter, ProvidedSchemaParser

/// Errors surfaced while rendering a `@WireletProvided` proxy. The offline
/// CLI (Phase 3) presents these to the developer.
public enum ProvidedSwiftBridgesEmitterError: Error, Equatable {
    /// A parameter or return type is not representable by the v1 proxy.
    /// Optionals (`T?`) are deferred; every other shape classifies via
    /// `InvokeArgClassifier`.
    case unsupportedType(service: String, method: String, type: String)
}

/// Scans Swift sources for `@WireletProvided` protocols and emits, per
/// protocol, a `<Service>WireletProxy` `final class` that forwards each
/// method across JNI to the Kotlin `<Service>NativeAdapter`. Pure string
/// rendering — the back-end for the `emit-wirelet-provided-swift-bridges`
/// CLI (Phase 3). Generated files are `#if os(Android)`; on Apple the
/// `@WireletProvided` protocol stays plain and no proxy is produced.
public struct ProvidedSwiftBridgesEmitter {
    public init() {}

    /// - Returns: one `(name, content)` pair per discovered service.
    ///   `name` is `<Service>+WireletProxy.swift`.
    public func emit(sources: [URL]) throws -> [(name: String, content: String)] {
        var results: [(name: String, content: String)] = []
        for url in sources {
            guard url.pathExtension == "swift" else { continue }
            let source = try String(contentsOf: url, encoding: .utf8)
            let schema = ProvidedSchemaParser.parse(source: source, fileName: url.lastPathComponent)
            for service in schema.services {
                let content = try renderFile(for: service)
                results.append((name: "\(service.name)+WireletProxy.swift", content: content))
            }
        }
        return results
    }

    // MARK: - File

    private func renderFile(for service: ProvidedService) throws -> String {
        let proxyName = "\(service.name)WireletProxy"
        let methods = try service.methods
            .map { try renderMethod(service: service, method: $0) }
            .joined(separator: "\n\n")
        return """
        // Generated by emit-wirelet-provided-swift-bridges.
        // Do not edit by hand.
        #if os(Android)
        import Foundation
        import Wirelet
        import WireletObservable

        final class \(proxyName): \(service.name) {
            let adapter: JObject

            init(adapter: JObject) {
                self.adapter = adapter
            }

        \(indent(methods, by: 4))
        }
        #endif
        """
    }

    // MARK: - Method

    private func renderMethod(service: ProvidedService, method: ProvidedMethod) throws -> String {
        let signature = methodSignature(method)
        let wireName = "\(method.name)Wire"

        // Encode each argument (and collect any byte-building prelude).
        var prelude: [String] = []
        var argExprs: [String] = []
        for (idx, param) in method.parameters.enumerated() {
            let use = param.internalName ?? param.label
            switch InvokeArgClassifier.classify(param.typeText) {
            case .primitive(let jni, _):
                switch jni {
                case "jlong":   argExprs.append(".long(Int64(\(use)))")
                case "jfloat":  argExprs.append(".float(\(use))")
                case "jdouble": argExprs.append(".double(\(use))")
                default:        argExprs.append(".int(Int32(\(use)))")  // jint
                }
            case .bool:
                argExprs.append(".bool(\(use))")
            case .string:
                argExprs.append(".string(\(use))")
            case .wireFormat:
                prelude.append("let arg\(idx)Bytes = [UInt8](\(use).encodeToData())")
                argExprs.append(".bytes(arg\(idx)Bytes)")
            case .array:
                prelude.append("""
                var writer\(idx) = WireFormatWriter()
                writer\(idx).writeVarint(UInt64(\(use).count))
                for element in \(use) { element.encode(into: &writer\(idx)) }
                let arg\(idx)Bytes = [UInt8](writer\(idx).data)
                """)
                argExprs.append(".bytes(arg\(idx)Bytes)")
            case .optionalPrimitive, .optionalString, .optionalWireFormat:
                throw ProvidedSwiftBridgesEmitterError.unsupportedType(
                    service: service.name, method: method.name, type: param.typeText
                )
            }
        }
        let argsTail = argExprs.isEmpty ? "" : ", [\(argExprs.joined(separator: ", "))]"
        let descriptor = try jniDescriptor(service: service, method: method)
        let call = try renderReturn(
            service: service, method: method,
            wireName: wireName, descriptor: descriptor, argsTail: argsTail
        )

        let body = (prelude + [call]).joined(separator: "\n")
        return """
        func \(signature) {
        \(indent(body, by: 4))
        }
        """
    }

    // MARK: - Return

    private func renderReturn(
        service: ProvidedService,
        method: ProvidedMethod,
        wireName: String,
        descriptor: String,
        argsTail: String
    ) throws -> String {
        let head = "method: \"\(wireName)\", signature: \"\(descriptor)\"\(argsTail)"
        guard let returnType = method.returnTypeText else {
            return "adapter.callVoid(\(head))"
        }
        switch InvokeArgClassifier.classify(returnType) {
        case .primitive(let jni, let cast):
            switch jni {
            case "jlong":   return "return \(cast)(adapter.callLong(\(head)) ?? 0)"
            case "jfloat":  return "return adapter.callFloat(\(head)) ?? 0"
            case "jdouble": return "return adapter.callDouble(\(head)) ?? 0"
            default:        return "return \(cast)(adapter.callInt(\(head)) ?? 0)"  // jint
            }
        case .bool:
            return "return adapter.callBool(\(head)) ?? false"
        case .string:
            return "return adapter.callString(\(head)) ?? \"\""
        case .wireFormat(let typeName):
            return """
            guard let bytes = adapter.callBytes(\(head)),
                  let value = try? \(typeName)(decoding: Data(bytes)) else {
                fatalError("\(service.name)WireletProxy.\(method.name): missing or invalid \(typeName) from Kotlin")
            }
            return value
            """
        case .array(let elementTypeName):
            return """
            guard let bytes = adapter.callBytes(\(head)) else {
                return []
            }
            var reader = WireFormatReader(data: Data(bytes))
            guard let count = try? reader.readVarint() else { return [] }
            var result: [\(elementTypeName)] = []
            result.reserveCapacity(Int(count))
            for _ in 0..<Int(count) {
                guard let element = try? \(elementTypeName)(from: &reader) else { return result }
                result.append(element)
            }
            return result
            """
        case .optionalPrimitive, .optionalString, .optionalWireFormat:
            throw ProvidedSwiftBridgesEmitterError.unsupportedType(
                service: service.name, method: method.name, type: returnType
            )
        }
    }

    // MARK: - JNI descriptor

    /// Builds the JNI method descriptor `(params)return`. Optional return types
    /// are mapped to `[B` here but are rejected by `renderReturn` before any
    /// proxy is emitted — so a misleading descriptor is never produced. Keep the
    /// two in sync if either side changes.
    private func jniDescriptor(service: ProvidedService, method: ProvidedMethod) throws -> String {
        let params = method.parameters
            .map { fragment(InvokeArgClassifier.classify($0.typeText)) }
            .joined()
        let ret: String
        if let returnType = method.returnTypeText {
            ret = fragment(InvokeArgClassifier.classify(returnType))
        } else {
            ret = "V"
        }
        return "(\(params))\(ret)"
    }

    private func fragment(_ kind: InvokeArgKind) -> String {
        switch kind {
        case .primitive(let jni, _):
            switch jni {
            case "jlong":   return "J"
            case "jfloat":  return "F"
            case "jdouble": return "D"
            default:        return "I"  // jint
            }
        case .bool:
            return "Z"
        case .string, .optionalString:
            return "Ljava/lang/String;"
        case .wireFormat, .optionalPrimitive, .optionalWireFormat, .array:
            return "[B"
        }
    }

    // MARK: - Signature text

    private func methodSignature(_ method: ProvidedMethod) -> String {
        let params = method.parameters.map { param -> String in
            if let inner = param.internalName {
                return "\(param.label) \(inner): \(param.typeText)"
            }
            return "\(param.label): \(param.typeText)"
        }.joined(separator: ", ")
        if let returnType = method.returnTypeText {
            return "\(method.name)(\(params)) -> \(returnType)"
        }
        return "\(method.name)(\(params))"
    }

    // MARK: - Indent

    private func indent(_ text: String, by spaces: Int) -> String {
        let pad = String(repeating: " ", count: spaces)
        return text
            .split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.isEmpty ? "" : pad + $0 }
            .joined(separator: "\n")
    }
}
