import Foundation
import SwiftParser
import SwiftSyntax
import WireletObservableSchema

/// Scans Swift source files for `@WireletObservable @Observable final class`
/// declarations and emits per-class `.swift` files containing global
/// `@_cdecl` JNI bridge functions.
///
/// This library is the rendering back-end for the
/// `emit-wirelet-observable-swift-bridges` CLI and the
/// `WireletObservableBridges` SwiftPM build tool plugin.
public struct SwiftBridgesEmitter {
    public init() {}

    /// Scans each URL for `@WireletObservable` classes and returns one
    /// `(name, content)` pair per discovered class.
    ///
    /// - Parameter sources: `.swift` files to parse.
    /// - Returns: Array of `(suggestedFileName, fileContent)` pairs.
    ///   Suggested file name is `<ClassName>+JNIBridges.swift`.
    public func emit(sources: [URL]) throws -> [(name: String, content: String)] {
        var results: [(name: String, content: String)] = []
        for url in sources {
            guard url.pathExtension == "swift" else { continue }
            let source = try String(contentsOf: url, encoding: .utf8)
            let schema = ObservableSchemaParser.parse(source: source, fileName: url.lastPathComponent)
            for viewModel in schema.viewModels {
                let content = renderFile(for: viewModel)
                results.append((name: "\(viewModel.name)+JNIBridges.swift", content: content))
            }
        }
        return results
    }

    // MARK: - File rendering

    private func renderFile(for viewModel: ObservableViewModel) -> String {
        let className = viewModel.name
        var bridges: [String] = []

        // Per-property track bridges
        for property in viewModel.properties {
            bridges.append(TrackBridgeEmitter.render(className: className, property: property))
        }

        // Constructor and destructor
        bridges.append(ConstructorEmitter.renderConstructor(className: className))
        bridges.append(ConstructorEmitter.renderDestructor(className: className))

        // Per-property setter bridges (only for var, not let)
        for property in viewModel.properties where property.isMutable {
            bridges.append(SetterBridgeEmitter.render(className: className, property: property))
        }

        // @WireletExpose invoke bridges
        for method in viewModel.methods {
            if let bridge = InvokeBridgeEmitter.render(className: className, method: method) {
                bridges.append(bridge)
            }
        }

        let body = bridges.joined(separator: "\n\n")
        return """
        // Generated by emit-wirelet-observable-swift-bridges.
        // Do not edit by hand.
        #if os(Android)
        import CWireletJNI
        import Foundation
        import Wirelet
        import WireletObservable

        \(body)
        #endif
        """
    }
}
