import Foundation
import SwiftParser
import SwiftSyntax
import WireletObservableSchema

/// Scans Swift source files for `@WireletObservable @Observable final class`
/// declarations and emits per-class `.swift` files containing global
/// `@_cdecl` JNI bridge functions.
///
/// This library is the rendering back-end for the
/// `emit-wirelet-observable-swift-bridges` CLI and the
/// `WireletObservableBridges` SwiftPM build tool plugin.
public struct SwiftBridgesEmitter {
    public init() {}

    /// Scans each URL for `@WireletObservable` classes and returns one
    /// `(name, content)` pair per discovered class, plus an optional
    /// `JNI_OnLoad` file when `jniConfig` is provided.
    ///
    /// - Parameters:
    ///   - sources: `.swift` files to parse.
    ///   - jniConfig: Optional JNI registration config read from a
    ///     `.wirelet-observable-jni.json` sidecar. When present, an extra
    ///     `__WireletObservableJNI_OnLoad.swift` file is appended to the
    ///     returned array consolidating all `RegisterNatives` calls.
    /// - Returns: Array of `(suggestedFileName, fileContent)` pairs.
    ///   Suggested file name is `<ClassName>+JNIBridges.swift` for bridge
    ///   files and `__WireletObservableJNI_OnLoad.swift` for the JNI_OnLoad.
    public func emit(
        sources: [URL],
        jniConfig: JNIRegistrationConfig? = nil,
    ) throws -> [(name: String, content: String)] {
        var results: [(name: String, content: String)] = []
        for url in sources {
            guard url.pathExtension == "swift" else { continue }
            let source = try String(contentsOf: url, encoding: .utf8)
            let schema = ObservableSchemaParser.parse(source: source, fileName: url.lastPathComponent)
            for viewModel in schema.viewModels {
                let content = renderFile(for: viewModel)
                results.append((name: "\(viewModel.name)+JNIBridges.swift", content: content))
            }
        }
        if let config = jniConfig, !config.viewModels.isEmpty {
            let jniContent = JNIOnLoadEmitter.renderFile(viewModels: config.viewModels)
            results.append((name: "__WireletObservableJNI_OnLoad.swift", content: jniContent))
        }
        return results
    }

    // MARK: - File rendering

    private func renderFile(for viewModel: ObservableViewModel) -> String {
        let className = viewModel.name
        var bridges: [String] = []

        // Per-property track bridges
        for property in viewModel.properties {
            bridges.append(TrackBridgeEmitter.render(className: className, property: property))
        }

        // Constructor and destructor
        bridges.append(ConstructorEmitter.renderConstructor(
            className: className,
            initParameters: viewModel.initParameters,
        ))
        bridges.append(ConstructorEmitter.renderDestructor(className: className))

        // Per-property setter bridges (only for var, not let)
        for property in viewModel.properties where property.isMutable {
            bridges.append(SetterBridgeEmitter.render(className: className, property: property))
        }

        // @WireletExpose invoke bridges
        for method in viewModel.methods {
            if let bridge = InvokeBridgeEmitter.render(className: className, method: method) {
                bridges.append(bridge)
            }
        }

        let body = bridges.joined(separator: "\n\n")
        return """
        // Generated by emit-wirelet-observable-swift-bridges.
        // Do not edit by hand.
        #if os(Android)
        import SwiftJavaJNICore
        import Foundation
        import Wirelet
        import WireletObservable

        \(body)
        #endif
        """
    }
}
